package netpolicy

import (
	"bytes"
	"fmt"
	"sort"
	"strings"
	"text/template"
)

// NetworkSpec mirrors the enclii.yaml network section.
// Passed in from the parsed EncliiYAMLNetwork to avoid a circular import.
type NetworkSpec struct {
	Services []ServiceSpec
	Custom   []CustomRule
}

// ServiceSpec declares network requirements for a single pod/service.
type ServiceSpec struct {
	Name    string   // pod app label value
	Label   string   // label key (default "app")
	Port    int      // container port for ingress
	Ingress []string // e.g. ["cloudflare-tunnel"]
	Egress  []string // e.g. ["dns","https","postgres","redis","http"]
}

// CustomRule declares a custom network policy rule.
type CustomRule struct {
	Name      string
	From      map[string]string // pod label selector
	To        map[string]string // pod label selector
	Port      int
	Direction string // "ingress","egress","both"
}

// effectiveLabel returns the label key, defaulting to "app".
func (s *ServiceSpec) effectiveLabel() string {
	if s.Label != "" {
		return s.Label
	}
	return "app"
}

// hasIngress returns true if the service accepts incoming traffic.
func (s *ServiceSpec) hasIngress(source string) bool {
	for _, ing := range s.Ingress {
		if ing == source {
			return true
		}
	}
	return false
}

// hasEgress returns true if the service needs the given egress type.
func (s *ServiceSpec) hasEgress(egressType string) bool {
	for _, eg := range s.Egress {
		if eg == egressType {
			return true
		}
	}
	return false
}

// GeneratePolicies produces a multi-document YAML string containing all
// NetworkPolicy resources for the given project, based on its network spec.
// The output always includes default-deny-ingress and default-deny-egress,
// plus per-service ingress/egress policies built from composable blocks.
func GeneratePolicies(namespace, projectName string, spec NetworkSpec) ([]byte, error) {
	var buf bytes.Buffer

	labels := map[string]string{
		"app.kubernetes.io/managed-by": "enclii",
		"app.kubernetes.io/component":  "network-policy",
		"enclii.dev/generated":         `"true"`,
		"enclii.dev/project":           projectName,
	}

	// Header comment
	fmt.Fprintf(&buf, "# =============================================================================\n")
	fmt.Fprintf(&buf, "# %s Namespace NetworkPolicies (auto-generated by enclii onboarding)\n", strings.Title(projectName)) //nolint:staticcheck
	fmt.Fprintf(&buf, "# =============================================================================\n")
	fmt.Fprintf(&buf, "# DO NOT EDIT — regenerate via POST /v1/admin/onboard or /v1/admin/netpolicy/regenerate\n")
	fmt.Fprintf(&buf, "# =============================================================================\n")

	// Default deny ingress
	buf.WriteString("\n# Default deny all ingress\n---\n")
	if err := renderDefaultDeny(&buf, namespace, "default-deny-ingress", "Ingress", labels); err != nil {
		return nil, fmt.Errorf("render default-deny-ingress: %w", err)
	}

	// Default deny egress
	buf.WriteString("\n# Default deny all egress\n---\n")
	if err := renderDefaultDeny(&buf, namespace, "default-deny-egress", "Egress", labels); err != nil {
		return nil, fmt.Errorf("render default-deny-egress: %w", err)
	}

	// Per-service policies
	for _, svc := range spec.Services {
		// Ingress policy
		if svc.hasIngress("cloudflare-tunnel") {
			comment := fmt.Sprintf("\n# Allow Cloudflare tunnel → %s (port %d)\n---\n", svc.Name, svc.Port)
			buf.WriteString(comment)
			if err := renderCloudflareIngress(&buf, namespace, svc, labels); err != nil {
				return nil, fmt.Errorf("render ingress for %s: %w", svc.Name, err)
			}
		}

		// Egress policy
		egressRules := buildEgressRules(svc)
		if len(egressRules) > 0 {
			comment := fmt.Sprintf("\n# Allow %s egress (%s)\n---\n", svc.Name, strings.Join(egressCategories(svc), " + "))
			buf.WriteString(comment)
			if err := renderEgress(&buf, namespace, svc, egressRules, labels); err != nil {
				return nil, fmt.Errorf("render egress for %s: %w", svc.Name, err)
			}
		}
	}

	// Custom rules
	for _, rule := range spec.Custom {
		if rule.Direction == "ingress" || rule.Direction == "both" {
			comment := fmt.Sprintf("\n# Custom ingress: %s\n---\n", rule.Name)
			buf.WriteString(comment)
			if err := renderCustomIngress(&buf, namespace, rule, labels); err != nil {
				return nil, fmt.Errorf("render custom ingress %s: %w", rule.Name, err)
			}
		}
		if rule.Direction == "egress" || rule.Direction == "both" {
			comment := fmt.Sprintf("\n# Custom egress: %s\n---\n", rule.Name)
			buf.WriteString(comment)
			if err := renderCustomEgress(&buf, namespace, rule, labels); err != nil {
				return nil, fmt.Errorf("render custom egress %s: %w", rule.Name, err)
			}
		}
	}

	return buf.Bytes(), nil
}

// egressCategories returns human-readable labels for the egress types a service uses.
func egressCategories(svc ServiceSpec) []string {
	var cats []string
	if svc.hasEgress("dns") {
		cats = append(cats, "DNS")
	}
	if svc.hasEgress("https") {
		cats = append(cats, "HTTPS")
	}
	if svc.hasEgress("http") {
		cats = append(cats, "HTTP")
	}
	if svc.hasEgress("postgres") {
		cats = append(cats, "PostgreSQL")
	}
	if svc.hasEgress("redis") {
		cats = append(cats, "Redis")
	}
	return cats
}

// egressRule represents a single egress rule block in the YAML output.
type egressRule struct {
	Comment string
	YAML    string
}

func buildEgressRules(svc ServiceSpec) []egressRule {
	var rules []egressRule

	// DNS is always included if any egress is declared
	if svc.hasEgress("dns") || len(svc.Egress) > 0 {
		rules = append(rules, egressRule{
			Comment: "DNS resolution",
			YAML: `    - to: []
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53`,
		})
	}

	if svc.hasEgress("https") {
		rules = append(rules, egressRule{
			Comment: "HTTPS egress for external APIs",
			YAML: `    - to: []
      ports:
        - protocol: TCP
          port: 443`,
		})
	}

	if svc.hasEgress("http") {
		rules = append(rules, egressRule{
			Comment: "HTTP egress",
			YAML: `    - to: []
      ports:
        - protocol: TCP
          port: 80`,
		})
	}

	if svc.hasEgress("postgres") {
		rules = append(rules, egressRule{
			Comment: "PostgreSQL in data namespace",
			YAML: `    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: data
          podSelector:
            matchLabels:
              app: postgres
      ports:
        - protocol: TCP
          port: 5432`,
		})
	}

	if svc.hasEgress("redis") {
		rules = append(rules, egressRule{
			Comment: "Redis in data namespace",
			YAML: `    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: data
          podSelector:
            matchLabels:
              app: redis
      ports:
        - protocol: TCP
          port: 6379`,
		})
	}

	return rules
}

// renderLabels formats a label map as YAML indented to the given level.
func renderLabels(labels map[string]string, indent int) string {
	if len(labels) == 0 {
		return ""
	}
	prefix := strings.Repeat(" ", indent)
	// Sort keys for deterministic output
	keys := make([]string, 0, len(labels))
	for k := range labels {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var lines []string
	for _, k := range keys {
		lines = append(lines, fmt.Sprintf("%s%s: %s", prefix, k, labels[k]))
	}
	return strings.Join(lines, "\n")
}

var defaultDenyTmpl = template.Must(template.New("defaultDeny").Parse(`apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Name }}
  namespace: {{ .Namespace }}
  labels:
{{ .Labels }}
spec:
  podSelector: {}
  policyTypes:
    - {{ .PolicyType }}
`))

func renderDefaultDeny(buf *bytes.Buffer, namespace, name, policyType string, labels map[string]string) error {
	return defaultDenyTmpl.Execute(buf, map[string]string{
		"Name":       name,
		"Namespace":  namespace,
		"Labels":     renderLabels(labels, 4),
		"PolicyType": policyType,
	})
}

var cloudflareIngressTmpl = template.Must(template.New("cfIngress").Parse(`apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .PolicyName }}
  namespace: {{ .Namespace }}
  labels:
{{ .Labels }}
spec:
  podSelector:
    matchLabels:
      {{ .LabelKey }}: {{ .LabelValue }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: cloudflare-tunnel
      ports:
        - protocol: TCP
          port: {{ .Port }}
`))

func renderCloudflareIngress(buf *bytes.Buffer, namespace string, svc ServiceSpec, labels map[string]string) error {
	return cloudflareIngressTmpl.Execute(buf, map[string]interface{}{
		"PolicyName": svc.Name + "-ingress",
		"Namespace":  namespace,
		"Labels":     renderLabels(labels, 4),
		"LabelKey":   svc.effectiveLabel(),
		"LabelValue": svc.Name,
		"Port":       svc.Port,
	})
}

func renderEgress(buf *bytes.Buffer, namespace string, svc ServiceSpec, rules []egressRule, labels map[string]string) error {
	fmt.Fprintf(buf, "apiVersion: networking.k8s.io/v1\n")
	fmt.Fprintf(buf, "kind: NetworkPolicy\n")
	fmt.Fprintf(buf, "metadata:\n")
	fmt.Fprintf(buf, "  name: %s-egress\n", svc.Name)
	fmt.Fprintf(buf, "  namespace: %s\n", namespace)
	fmt.Fprintf(buf, "  labels:\n")
	fmt.Fprintf(buf, "%s\n", renderLabels(labels, 4))
	fmt.Fprintf(buf, "spec:\n")
	fmt.Fprintf(buf, "  podSelector:\n")
	fmt.Fprintf(buf, "    matchLabels:\n")
	fmt.Fprintf(buf, "      %s: %s\n", svc.effectiveLabel(), svc.Name)
	fmt.Fprintf(buf, "  policyTypes:\n")
	fmt.Fprintf(buf, "    - Egress\n")
	fmt.Fprintf(buf, "  egress:\n")

	for _, r := range rules {
		fmt.Fprintf(buf, "    # %s\n", r.Comment)
		fmt.Fprintf(buf, "%s\n", r.YAML)
	}

	return nil
}

func renderCustomIngress(buf *bytes.Buffer, namespace string, rule CustomRule, labels map[string]string) error {
	policyName := slugify(rule.Name) + "-custom-ingress"

	fmt.Fprintf(buf, "apiVersion: networking.k8s.io/v1\n")
	fmt.Fprintf(buf, "kind: NetworkPolicy\n")
	fmt.Fprintf(buf, "metadata:\n")
	fmt.Fprintf(buf, "  name: %s\n", policyName)
	fmt.Fprintf(buf, "  namespace: %s\n", namespace)
	fmt.Fprintf(buf, "  labels:\n")
	fmt.Fprintf(buf, "%s\n", renderLabels(labels, 4))
	fmt.Fprintf(buf, "spec:\n")

	// Pod selector targets the "to" pods
	if len(rule.To) > 0 {
		fmt.Fprintf(buf, "  podSelector:\n")
		fmt.Fprintf(buf, "    matchLabels:\n")
		fmt.Fprintf(buf, "%s\n", renderLabels(rule.To, 6))
	} else {
		fmt.Fprintf(buf, "  podSelector: {}\n")
	}

	fmt.Fprintf(buf, "  policyTypes:\n")
	fmt.Fprintf(buf, "    - Ingress\n")
	fmt.Fprintf(buf, "  ingress:\n")

	if len(rule.From) > 0 {
		fmt.Fprintf(buf, "    - from:\n")
		fmt.Fprintf(buf, "        - podSelector:\n")
		fmt.Fprintf(buf, "            matchLabels:\n")
		fmt.Fprintf(buf, "%s\n", renderLabels(rule.From, 14))
	} else {
		fmt.Fprintf(buf, "    - from: []\n")
	}

	fmt.Fprintf(buf, "      ports:\n")
	fmt.Fprintf(buf, "        - protocol: TCP\n")
	fmt.Fprintf(buf, "          port: %d\n", rule.Port)

	return nil
}

func renderCustomEgress(buf *bytes.Buffer, namespace string, rule CustomRule, labels map[string]string) error {
	policyName := slugify(rule.Name) + "-custom-egress"

	fmt.Fprintf(buf, "apiVersion: networking.k8s.io/v1\n")
	fmt.Fprintf(buf, "kind: NetworkPolicy\n")
	fmt.Fprintf(buf, "metadata:\n")
	fmt.Fprintf(buf, "  name: %s\n", policyName)
	fmt.Fprintf(buf, "  namespace: %s\n", namespace)
	fmt.Fprintf(buf, "  labels:\n")
	fmt.Fprintf(buf, "%s\n", renderLabels(labels, 4))
	fmt.Fprintf(buf, "spec:\n")

	// Pod selector targets the "from" pods
	if len(rule.From) > 0 {
		fmt.Fprintf(buf, "  podSelector:\n")
		fmt.Fprintf(buf, "    matchLabels:\n")
		fmt.Fprintf(buf, "%s\n", renderLabels(rule.From, 6))
	} else {
		fmt.Fprintf(buf, "  podSelector: {}\n")
	}

	fmt.Fprintf(buf, "  policyTypes:\n")
	fmt.Fprintf(buf, "    - Egress\n")
	fmt.Fprintf(buf, "  egress:\n")

	if len(rule.To) > 0 {
		fmt.Fprintf(buf, "    - to:\n")
		fmt.Fprintf(buf, "        - podSelector:\n")
		fmt.Fprintf(buf, "            matchLabels:\n")
		fmt.Fprintf(buf, "%s\n", renderLabels(rule.To, 14))
	} else {
		fmt.Fprintf(buf, "    - to: []\n")
	}

	fmt.Fprintf(buf, "      ports:\n")
	fmt.Fprintf(buf, "        - protocol: TCP\n")
	fmt.Fprintf(buf, "          port: %d\n", rule.Port)

	return nil
}

// slugify converts a name to a K8s-compatible slug.
func slugify(name string) string {
	s := strings.ToLower(name)
	s = strings.ReplaceAll(s, " ", "-")
	s = strings.ReplaceAll(s, "_", "-")
	return s
}
