apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: arc-runners-secrets
  namespace: arc-runners
  labels:
    app.kubernetes.io/managed-by: enclii
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: vault-store
    kind: ClusterSecretStore
  target:
    name: arc-runners-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: GITHUB_APP_ID
      remoteRef:
        key: secret/arc-runners
        property: github_app_id
    - secretKey: GITHUB_APP_INSTALLATION_ID
      remoteRef:
        key: secret/arc-runners
        property: github_app_installation_id
    - secretKey: GITHUB_APP_PRIVATE_KEY
      remoteRef:
        key: secret/arc-runners
        property: github_app_private_key
