apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-secrets
  namespace: cloudflare-tunnel
  labels:
    app.kubernetes.io/managed-by: enclii
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: vault-store
    kind: ClusterSecretStore
  target:
    name: cloudflare-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: TUNNEL_TOKEN
      remoteRef:
        key: secret/cloudflare
        property: tunnel_token
