apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: data-secrets
  namespace: data
  labels:
    app.kubernetes.io/managed-by: enclii
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: vault-store
    kind: ClusterSecretStore
  target:
    name: data-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: secret/data
        property: postgres_password
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: secret/data
        property: redis_password
    - secretKey: PGBOUNCER_USERLIST
      remoteRef:
        key: secret/data
        property: pgbouncer_userlist
    - secretKey: R2_BACKUP_ACCESS_KEY_ID
      remoteRef:
        key: secret/data
        property: r2_backup_access_key_id
    - secretKey: R2_BACKUP_SECRET_ACCESS_KEY
      remoteRef:
        key: secret/data
        property: r2_backup_secret_access_key
    - secretKey: R2_BACKUP_ENDPOINT
      remoteRef:
        key: secret/data
        property: r2_backup_endpoint
    - secretKey: CLOUDFLARE_API_TOKEN
      remoteRef:
        key: secret/data
        property: cloudflare_api_token
    - secretKey: GITHUB_BACKUP_TOKEN
      remoteRef:
        key: secret/data
        property: github_backup_token
