apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: enclii-secrets
  namespace: enclii
  labels:
    app.kubernetes.io/managed-by: enclii
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: vault-store
    kind: ClusterSecretStore
  target:
    name: enclii-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: secret/enclii
        property: database_url
    - secretKey: REDIS_URL
      remoteRef:
        key: secret/enclii
        property: redis_url
    - secretKey: JANUA_CLIENT_ID
      remoteRef:
        key: secret/enclii
        property: janua_client_id
    - secretKey: JANUA_CLIENT_SECRET
      remoteRef:
        key: secret/enclii
        property: janua_client_secret
    - secretKey: GITHUB_WEBHOOK_SECRET
      remoteRef:
        key: secret/enclii
        property: github_webhook_secret
    - secretKey: internal-api-key
      remoteRef:
        key: secret/enclii
        property: switchyard_api_key
    - secretKey: JWT_SECRET
      remoteRef:
        key: secret/enclii
        property: jwt_secret
    - secretKey: OIDC_ISSUER
      remoteRef:
        key: secret/enclii
        property: oidc_issuer
    - secretKey: OIDC_REDIRECT_URI
      remoteRef:
        key: secret/enclii
        property: oidc_redirect_uri
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: secret/enclii
        property: postgres_password
    - secretKey: R2_ACCESS_KEY_ID
      remoteRef:
        key: secret/enclii
        property: r2_access_key_id
    - secretKey: R2_SECRET_ACCESS_KEY
      remoteRef:
        key: secret/enclii
        property: r2_secret_access_key
    - secretKey: R2_ENDPOINT
      remoteRef:
        key: secret/enclii
        property: r2_endpoint
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: secret/enclii
        property: redis_password
    - secretKey: GITHUB_TOKEN
      remoteRef:
        key: secret/enclii
        property: github_token
    - secretKey: CLOUDFLARE_API_TOKEN
      remoteRef:
        key: secret/enclii
        property: cloudflare_api_token
    - secretKey: CLOUDFLARE_TUNNEL_TOKEN
      remoteRef:
        key: secret/enclii
        property: cloudflare_tunnel_token
    - secretKey: ARGOCD_WEBHOOK_SECRET
      remoteRef:
        key: secret/enclii
        property: argocd_webhook_secret
    - secretKey: DISPATCH_SECRET_KEY
      remoteRef:
        key: secret/enclii
        property: dispatch_secret_key
    - secretKey: STATUS_ADMIN_SECRET
      remoteRef:
        key: secret/enclii
        property: status_admin_secret
    - secretKey: WAYBILL_API_KEY
      remoteRef:
        key: secret/enclii
        property: waybill_api_key
    - secretKey: ROUNDHOUSE_REGISTRY_PASSWORD
      remoteRef:
        key: secret/enclii
        property: roundhouse_registry_password
    - secretKey: POSTHOG_API_KEY
      remoteRef:
        key: secret/enclii
        property: posthog_api_key
