apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: enclii-builds-secrets
  namespace: enclii-builds
  labels:
    app.kubernetes.io/managed-by: enclii
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: vault-store
    kind: ClusterSecretStore
  target:
    name: enclii-builds-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: GIT_USERNAME
      remoteRef:
        key: secret/enclii-builds
        property: git_username
    - secretKey: GIT_PASSWORD
      remoteRef:
        key: secret/enclii-builds
        property: git_password
    - secretKey: REGISTRY_PASSWORD
      remoteRef:
        key: secret/enclii-builds
        property: registry_password
