apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: janua-secrets
  namespace: janua
  labels:
    app.kubernetes.io/managed-by: enclii
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: vault-store
    kind: ClusterSecretStore
  target:
    name: janua-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: secret/janua
        property: database_url
    - secretKey: REDIS_URL
      remoteRef:
        key: secret/janua
        property: redis_url
    - secretKey: JWT_SIGNING_KEY
      remoteRef:
        key: secret/janua
        property: jwt_signing_key
    - secretKey: GITHUB_CLIENT_ID
      remoteRef:
        key: secret/janua
        property: github_client_id
    - secretKey: GITHUB_CLIENT_SECRET
      remoteRef:
        key: secret/janua
        property: github_client_secret
    - secretKey: SMTP_PASSWORD
      remoteRef:
        key: secret/janua
        property: smtp_password
    - secretKey: SECRET_KEY
      remoteRef:
        key: secret/janua
        property: secret_key
    - secretKey: FIELD_ENCRYPTION_KEY
      remoteRef:
        key: secret/janua
        property: field_encryption_key
    - secretKey: NPM_MADFAM_TOKEN
      remoteRef:
        key: secret/janua
        property: npm_madfam_token
