apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kyverno-secrets
  namespace: kyverno
  labels:
    app.kubernetes.io/managed-by: enclii
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: vault-store
    kind: ClusterSecretStore
  target:
    name: kyverno-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: COSIGN_PUBLIC_KEY
      remoteRef:
        key: secret/kyverno
        property: cosign_public_key
