apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: madfam-site-secrets
  namespace: madfam-site
  labels:
    app.kubernetes.io/managed-by: enclii
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: vault-store
    kind: ClusterSecretStore
  target:
    name: madfam-site-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: NEXT_PUBLIC_POSTHOG_KEY
      remoteRef:
        key: secret/madfam-site
        property: next_public_posthog_key
    - secretKey: SESSION_SECRET
      remoteRef:
        key: secret/madfam-site
        property: session_secret
