apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: monitoring-secrets
  namespace: monitoring
  labels:
    app.kubernetes.io/managed-by: enclii
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: vault-store
    kind: ClusterSecretStore
  target:
    name: monitoring-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: ALERTMANAGER_SMTP_PASSWORD
      remoteRef:
        key: secret/monitoring
        property: alertmanager_smtp_password
    - secretKey: GRAFANA_ADMIN_PASSWORD
      remoteRef:
        key: secret/monitoring
        property: grafana_admin_password
    - secretKey: GRAFANA_SMTP_PASSWORD
      remoteRef:
        key: secret/monitoring
        property: grafana_smtp_password
