apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: posthog-secrets
  namespace: posthog
  labels:
    app.kubernetes.io/managed-by: enclii
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: vault-store
    kind: ClusterSecretStore
  target:
    name: posthog-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: POSTHOG_DB_PASSWORD
      remoteRef:
        key: secret/posthog
        property: posthog_db_password
    - secretKey: POSTHOG_SECRET_KEY
      remoteRef:
        key: secret/posthog
        property: posthog_secret_key
