apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tezca-secrets
  namespace: tezca
  labels:
    app.kubernetes.io/managed-by: enclii
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: vault-store
    kind: ClusterSecretStore
  target:
    name: tezca-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: secret/tezca
        property: database_url
    - secretKey: REDIS_URL
      remoteRef:
        key: secret/tezca
        property: redis_url
    - secretKey: SECRET_KEY
      remoteRef:
        key: secret/tezca
        property: secret_key
    - secretKey: ELASTICSEARCH_URL
      remoteRef:
        key: secret/tezca
        property: elasticsearch_url
    - secretKey: R2_ACCESS_KEY_ID
      remoteRef:
        key: secret/tezca
        property: r2_access_key_id
    - secretKey: R2_SECRET_ACCESS_KEY
      remoteRef:
        key: secret/tezca
        property: r2_secret_access_key
    - secretKey: R2_ENDPOINT
      remoteRef:
        key: secret/tezca
        property: r2_endpoint
    - secretKey: POSTHOG_API_KEY
      remoteRef:
        key: secret/tezca
        property: posthog_api_key
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        key: secret/tezca
        property: oidc_client_secret
    - secretKey: DJANGO_SECRET_KEY
      remoteRef:
        key: secret/tezca
        property: django_secret_key
    - secretKey: CELERY_BROKER_URL
      remoteRef:
        key: secret/tezca
        property: celery_broker_url
