apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: ghcr.io/madfam-org/enclii/dispatch
    newName: ghcr.io/madfam-org/enclii/dispatch
    digest: sha256:bdfbf07eba72ade4aa269ee7ad2c4ca9b30431c7a5d7ffb4debc49e430f262c7
