apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- digest: sha256:56940cfeac40161ef7cf028dba9dfd778ac496bedea5de247efe837cb686f42d
  name: ghcr.io/madfam-org/enclii/dispatch
  newName: ghcr.io/madfam-org/enclii/dispatch
