apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- digest: sha256:f74c604929540a014d94ca2918bc4822ad93470367ff9409931c60b9183c9ed9
  name: ghcr.io/madfam-org/enclii/dispatch
  newName: ghcr.io/madfam-org/enclii/dispatch
