---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pgbackrest-r2-credentials
  namespace: data
  labels:
    app.kubernetes.io/name: pgbackrest
    app.kubernetes.io/component: backup
    app.kubernetes.io/part-of: enclii
    app.kubernetes.io/managed-by: enclii
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: data-kubernetes-store
    kind: ClusterSecretStore
  target:
    name: pgbackrest-r2-credentials
    creationPolicy: Merge
    deletionPolicy: Retain
  data:
    - secretKey: R2_ACCOUNT_ID
      remoteRef:
        key: pgbackrest-r2-credentials-source
        property: R2_ACCOUNT_ID
    - secretKey: PGBACKREST_REPO1_S3_KEY
      remoteRef:
        key: pgbackrest-r2-credentials-source
        property: PGBACKREST_REPO1_S3_KEY
    - secretKey: PGBACKREST_REPO1_S3_KEY_SECRET
      remoteRef:
        key: pgbackrest-r2-credentials-source
        property: PGBACKREST_REPO1_S3_KEY_SECRET
    - secretKey: PGBACKREST_REPO1_CIPHER_PASS
      remoteRef:
        key: pgbackrest-r2-credentials-source
        property: PGBACKREST_REPO1_CIPHER_PASS
    - secretKey: PGBACKREST_REPO1_S3_ENDPOINT
      remoteRef:
        key: pgbackrest-r2-credentials-source
        property: PGBACKREST_REPO1_S3_ENDPOINT
