package cmd

import (
	"fmt"
	"io"
	"regexp"
	"strconv"
	"strings"

	"github.com/spf13/pflag"

	"github.com/madfam-org/enclii/packages/sdk-go/pkg/types"
)

// Generated credentials on `enclii onboard` and `enclii onboard ensure`.
//
// Every value behind these flags is generated by Switchyard, written into the
// project Secret and never returned: the CLI sends names and sizes, and prints
// names and actions. Validation here mirrors the server's so a bad flag fails
// before any network call; the server validates again.

const (
	minGeneratedBytes      = 16
	maxGeneratedBytes      = 128
	maxRoleConnectionLimit = 20
	defaultAppRoleConnLim  = 5
	defaultAppRoleURLKey   = "APP_DATABASE_URL" // #nosec G101 -- Secret key name, not a value // pragma: allowlist secret
	defaultOwnerURLKey     = "DATABASE_URL"     // #nosec G101 -- Secret key name, not a value // pragma: allowlist secret
)

var (
	cliSQLIdentifierRe = regexp.MustCompile(`^[a-z][a-z0-9_]{0,62}$`)
	cliSecretKeyRe     = regexp.MustCompile(`^[A-Z_][A-Z0-9_]{0,127}$`)
	// r2SecretKeys are written by R2 provisioning; nothing generated may reuse them.
	r2SecretKeys = []string{"R2_BUCKET_NAME", "R2_ENDPOINT_URL", "R2_ACCESS_KEY_ID", "R2_SECRET_ACCESS_KEY", "STORAGE_BACKEND"}
)

// generatedCredentialFlags are the flags shared by onboard and onboard ensure.
type generatedCredentialFlags struct {
	generateDBPassword bool
	rotateDBPassword   bool
	dbURLKey           string
	dbConnectionLimit  int

	appRole               string
	appRoleConnLimit      int
	appRoleURLKey         string
	appRolePasswordKey    string
	rotateAppRolePassword bool

	generateSecrets []string // KEY or KEY:bytes
	rotateSecrets   []string // KEY
}

func (g *generatedCredentialFlags) register(fs *pflag.FlagSet) {
	fs.BoolVar(&g.generateDBPassword, "generate-db-password", false,
		"Generate the database owner password server-side; its URL is written to the project Secret (no prompt)")
	fs.BoolVar(&g.rotateDBPassword, "rotate-db-password", false,
		"Generate a NEW owner password and replace the stored URL (implies --generate-db-password)")
	fs.StringVar(&g.dbURLKey, "db-url-key", "", "Secret key for the generated owner URL (default DATABASE_URL)")
	fs.IntVar(&g.dbConnectionLimit, "db-connection-limit", 0, "CONNECTION LIMIT for the owner role, 1-20 (default: unchanged)")

	fs.StringVar(&g.appRole, "app-role", "", "Runtime database role to create, e.g. <db>_app (generated password)")
	fs.IntVar(&g.appRoleConnLimit, "app-role-connection-limit", defaultAppRoleConnLim, "CONNECTION LIMIT for --app-role, 1-20")
	fs.StringVar(&g.appRoleURLKey, "app-role-url-key", defaultAppRoleURLKey, "Secret key for the app role's connection URL")
	fs.StringVar(&g.appRolePasswordKey, "app-role-password-key", "", "Also store the app role's bare password under this Secret key (for split connection settings)")
	fs.BoolVar(&g.rotateAppRolePassword, "rotate-app-role-password", false, "Generate a NEW password for an existing --app-role")

	fs.StringArrayVar(&g.generateSecrets, "generate-secret", nil,
		"Generate a project-Secret value server-side: KEY or KEY:bytes (16-128, default 32). Repeatable")
	fs.StringArrayVar(&g.rotateSecrets, "rotate-secret", nil, "Replace an existing generated value: KEY. Repeatable")
}

// generatesOwnerPassword reports whether the owner password is generated.
func (g generatedCredentialFlags) generatesOwnerPassword() bool {
	return g.generateDBPassword || g.rotateDBPassword
}

// validate checks the flags without any network call. dbName is --db-name;
// typedPassword reports whether --db-password was given.
func (g generatedCredentialFlags) validate(dbName string, typedPassword bool) error {
	if g.generatesOwnerPassword() {
		if typedPassword {
			return fmt.Errorf("--db-password and --generate-db-password/--rotate-db-password are mutually exclusive")
		}
		if dbName == "" {
			return fmt.Errorf("--generate-db-password needs --db-name")
		}
	} else if g.dbURLKey != "" {
		return fmt.Errorf("--db-url-key only applies with --generate-db-password")
	}
	if g.dbConnectionLimit != 0 {
		if err := checkConnectionLimit(g.dbConnectionLimit, "--db-connection-limit"); err != nil {
			return err
		}
	}

	owned := map[string]string{}
	for _, k := range r2SecretKeys {
		owned[k] = "R2 provisioning"
	}
	claim := func(key, by string) error {
		if !cliSecretKeyRe.MatchString(key) {
			return fmt.Errorf("%s: secret key %q is invalid (must match ^[A-Z_][A-Z0-9_]{0,127}$)", by, key)
		}
		if prev, ok := owned[key]; ok {
			return fmt.Errorf("secret key %s is written by both %s and %s", key, prev, by)
		}
		owned[key] = by
		return nil
	}
	if g.generatesOwnerPassword() {
		key := g.dbURLKey
		if key == "" {
			key = defaultOwnerURLKey
		}
		if err := claim(key, "--db-url-key"); err != nil {
			return err
		}
	}

	if g.appRole == "" {
		if g.rotateAppRolePassword || g.appRolePasswordKey != "" {
			return fmt.Errorf("--rotate-app-role-password and --app-role-password-key need --app-role")
		}
	} else {
		if dbName == "" {
			return fmt.Errorf("--app-role needs --db-name (the database the role connects to)")
		}
		if err := checkAppRoleName(g.appRole, dbName); err != nil {
			return err
		}
		if err := checkConnectionLimit(g.appRoleConnLimit, "--app-role-connection-limit"); err != nil {
			return err
		}
		if err := claim(g.appRoleURLKey, "--app-role-url-key"); err != nil {
			return err
		}
		if g.appRolePasswordKey != "" {
			if err := claim(g.appRolePasswordKey, "--app-role-password-key"); err != nil {
				return err
			}
		}
	}

	specs, err := g.secretSpecs()
	if err != nil {
		return err
	}
	for _, s := range specs {
		if err := claim(s.Key, "--generate-secret"); err != nil {
			return err
		}
	}
	return nil
}

// checkConflictsWithSecretsFile rejects a secrets-file key that would shadow a
// generated value.
func (g generatedCredentialFlags) checkConflictsWithSecretsFile(entries []types.SecretEntry) error {
	generated := map[string]bool{}
	if g.generatesOwnerPassword() {
		key := g.dbURLKey
		if key == "" {
			key = defaultOwnerURLKey
		}
		generated[key] = true
	}
	if g.appRole != "" {
		generated[g.appRoleURLKey] = true
		if g.appRolePasswordKey != "" {
			generated[g.appRolePasswordKey] = true // pragma: allowlist secret -- flag/field names, not a value
		}
	}
	specs, _ := g.secretSpecs()
	for _, s := range specs {
		generated[s.Key] = true
	}
	for _, e := range entries {
		if generated[e.Key] {
			return fmt.Errorf("secrets file key %s collides with a generated value; remove it from the file", e.Key)
		}
	}
	return nil
}

// secretSpecs parses --generate-secret and --rotate-secret. A --rotate-secret
// key that is not also in --generate-secret is generated at the default size.
func (g generatedCredentialFlags) secretSpecs() ([]types.GeneratedSecretSpec, error) {
	var specs []types.GeneratedSecretSpec
	index := map[string]int{}
	for _, raw := range g.generateSecrets {
		key, bytesStr, hasSize := strings.Cut(raw, ":")
		spec := types.GeneratedSecretSpec{Key: key}
		if hasSize {
			n, err := strconv.Atoi(bytesStr)
			if err != nil || n < minGeneratedBytes || n > maxGeneratedBytes {
				return nil, fmt.Errorf("--generate-secret %s: size must be %d-%d bytes", raw, minGeneratedBytes, maxGeneratedBytes)
			}
			spec.Bytes = n
		}
		if !cliSecretKeyRe.MatchString(key) {
			return nil, fmt.Errorf("--generate-secret: key %q is invalid (must match ^[A-Z_][A-Z0-9_]{0,127}$)", key) // pragma: allowlist secret -- flag/field names, not a value
		}
		if _, dup := index[key]; dup {
			return nil, fmt.Errorf("--generate-secret %s given twice", key)
		}
		index[key] = len(specs)
		specs = append(specs, spec)
	}
	for _, key := range g.rotateSecrets {
		if !cliSecretKeyRe.MatchString(key) {
			return nil, fmt.Errorf("--rotate-secret: key %q is invalid", key) // pragma: allowlist secret -- flag/field names, not a value
		}
		if i, ok := index[key]; ok {
			specs[i].Rotate = true
			continue
		}
		index[key] = len(specs)
		specs = append(specs, types.GeneratedSecretSpec{Key: key, Rotate: true})
	}
	return specs, nil
}

// apply adds the generation fields to req. ownerSpec is the request's
// Postgres spec when the command provisions the owner (nil otherwise).
func (g generatedCredentialFlags) apply(req *types.OnboardingRequest, dbName string) error {
	if req.ProvisionPostgres != nil && g.generatesOwnerPassword() {
		req.ProvisionPostgres.RolePassword = ""                   // pragma: allowlist secret -- clears the field; no value
		req.ProvisionPostgres.GeneratePassword = true             // pragma: allowlist secret -- boolean flag, not a value
		req.ProvisionPostgres.RotatePassword = g.rotateDBPassword // pragma: allowlist secret -- flag/field names, not a value
		req.ProvisionPostgres.URLSecretKey = g.dbURLKey           // pragma: allowlist secret -- flag/field names, not a value
		req.ProvisionPostgres.ConnectionLimit = g.dbConnectionLimit
	}
	if g.appRole != "" {
		req.ProvisionAppRole = &types.AppRoleSpec{
			RoleName:          g.appRole,
			DatabaseName:      dbName,
			ConnectionLimit:   g.appRoleConnLimit,
			URLSecretKey:      g.appRoleURLKey,         // pragma: allowlist secret -- flag/field names, not a value
			PasswordSecretKey: g.appRolePasswordKey,    // pragma: allowlist secret -- flag/field names, not a value
			RotatePassword:    g.rotateAppRolePassword, // pragma: allowlist secret -- flag/field names, not a value
		}
	}
	specs, err := g.secretSpecs()
	if err != nil {
		return err
	}
	req.GenerateSecrets = specs // pragma: allowlist secret -- flag/field names, not a value
	return nil
}

func checkConnectionLimit(n int, flag string) error {
	if n < 1 || n > maxRoleConnectionLimit {
		return fmt.Errorf("%s %d is out of range 1-%d (the shared Postgres has a 100-connection budget)", flag, n, maxRoleConnectionLimit)
	}
	return nil
}

// checkAppRoleName mirrors the server's naming rule: "<db>_<suffix>", a valid
// identifier, never a platform role.
func checkAppRoleName(role, dbName string) error {
	if !cliSQLIdentifierRe.MatchString(role) {
		return fmt.Errorf("--app-role %q is invalid: must match ^[a-z][a-z0-9_]{0,62}$", role)
	}
	if role == "postgres" || role == "pgbouncer_admin" || strings.HasPrefix(role, "pg_") {
		return fmt.Errorf("--app-role %q is a reserved role name", role)
	}
	if !strings.HasPrefix(role, dbName+"_") || len(role) == len(dbName)+1 {
		return fmt.Errorf("--app-role %q must start with %q, e.g. %q", role, dbName+"_", dbName+"_app")
	}
	return nil
}

// printGenerationPlan lists, for a dry run, what the server would generate:
// role and key names only.
func printGenerationPlan(w io.Writer, req types.OnboardingRequest) {
	pg := req.ProvisionPostgres
	if (pg == nil || !pg.GeneratePassword) && req.ProvisionAppRole == nil && len(req.GenerateSecrets) == 0 {
		return
	}
	_, _ = fmt.Fprintln(w, "    Generated server-side (values are never printed or returned):")
	if pg != nil && pg.GeneratePassword {
		key := pg.URLSecretKey
		if key == "" {
			key = defaultOwnerURLKey
		}
		mode := "kept if it already exists"
		if pg.RotatePassword {
			mode = "ROTATED"
		}
		_, _ = fmt.Fprintf(w, "        - owner role %q password -> Secret key %s (%s)\n", ownerRole(pg), key, mode)
	}
	if ar := req.ProvisionAppRole; ar != nil {
		mode := "kept if it already exists"
		if ar.RotatePassword {
			mode = "ROTATED"
		}
		keys := ar.URLSecretKey
		if ar.PasswordSecretKey != "" {
			keys += ", " + ar.PasswordSecretKey
		}
		_, _ = fmt.Fprintf(w, "        - app role %q on %q, CONNECTION LIMIT %d, no BYPASSRLS -> Secret key(s) %s (%s)\n",
			ar.RoleName, ar.DatabaseName, ar.ConnectionLimit, keys, mode)
	}
	for _, s := range req.GenerateSecrets {
		n := s.Bytes
		if n == 0 {
			n = 32
		}
		mode := "kept if it already exists"
		if s.Rotate {
			mode = "ROTATED"
		}
		_, _ = fmt.Fprintf(w, "        - Secret key %s: %d random bytes, base64url (%s)\n", s.Key, n, mode)
	}
}

func ownerRole(pg *types.PostgresProvisionSpec) string {
	if pg.RoleName != "" {
		return pg.RoleName
	}
	return pg.DatabaseName
}

// printGeneratedCredentials renders the server's generated_credentials list:
// kind, name, keys and action only. Any other field is ignored, so even a
// server that wrongly sent a value could not get it printed here.
func printGeneratedCredentials(w io.Writer, result map[string]interface{}) {
	list, ok := result["generated_credentials"].([]interface{})
	if !ok || len(list) == 0 {
		return
	}
	_, _ = fmt.Fprintln(w)
	_, _ = fmt.Fprintln(w, "  Generated credentials (stored in the Secret, never shown):")
	for _, item := range list {
		m, ok := item.(map[string]interface{})
		if !ok {
			continue
		}
		var keys []string
		if raw, ok := m["keys"].([]interface{}); ok {
			for _, k := range raw {
				if s, ok := k.(string); ok {
					keys = append(keys, s)
				}
			}
		}
		_, _ = fmt.Fprintf(w, "    - %v %v: %v (Secret %v: %s)\n",
			m["kind"], m["name"], m["action"], m["secret"], strings.Join(keys, ", "))
	}
}
