apiVersion: v1
kind: Secret
metadata:
  name: verdaccio-auth
  namespace: npm-registry
  labels:
    app.kubernetes.io/name: verdaccio
    app.kubernetes.io/component: auth
type: Opaque
stringData:
  htpasswd: |
    admin@madfam.io:$2y$05$IY11HSd/t8RAzBveyXBvOu5K3kbJ/L9hp8Y6KcpFctB3UiEJzSIli
