---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: npm-token-rotation-token
  namespace: npm-registry
  labels:
    app.kubernetes.io/name: verdaccio
    app.kubernetes.io/component: token-rotation
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: enclii-builds-kubernetes-store
    kind: ClusterSecretStore
  target:
    name: npm-token-rotation-creds
    creationPolicy: Merge
    deletionPolicy: Retain
  data:
    - secretKey: token
      remoteRef:
        key: npm-madfam-token
        property: token
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: npm-token-rotation-github-token
  namespace: npm-registry
  labels:
    app.kubernetes.io/name: verdaccio
    app.kubernetes.io/component: token-rotation
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: kubernetes-store
    kind: ClusterSecretStore
  target:
    name: npm-token-rotation-creds
    creationPolicy: Merge
    deletionPolicy: Retain
  data:
    - secretKey: gh_token
      remoteRef:
        key: enclii-github-token
        property: token
