apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: status-base

resources:
  - deployment.yaml
  - service.yaml

# Common labels applied to all resources
commonLabels:
  app.kubernetes.io/name: status
  app.kubernetes.io/part-of: enclii
  app.kubernetes.io/managed-by: kustomize

images:
  - name: ghcr.io/madfam-org/enclii/enclii-status
    newName: ghcr.io/madfam-org/enclii/enclii-status
    digest: sha256:a337ab0709a21e57e475d925e2221d62a9d4530c323c92d37cd7e4760c142155
