apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: status-base

resources:
- deployment.yaml
- service.yaml

# Common labels applied to all resources
commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/name: status
  app.kubernetes.io/part-of: enclii

images:
- digest: sha256:fe6e25f49a2c42c3d4924effce1f9c4e47c48f2c6d1af6c0cc3cabcd18c5f77f
  name: ghcr.io/madfam-org/enclii/enclii-status
  newName: ghcr.io/madfam-org/enclii/enclii-status
