apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: status-base

resources:
- deployment.yaml
- service.yaml

# Common labels applied to all resources
commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/name: status
  app.kubernetes.io/part-of: enclii

images:
- digest: sha256:cc8a1f6134905a5d6360d90cd816bcc9a72d1b286859d562b0ddf28726a43a7c
  name: ghcr.io/madfam-org/enclii/enclii-status
  newName: ghcr.io/madfam-org/enclii/enclii-status
