---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: waybill
  labels:
    app: waybill
    app.kubernetes.io/name: waybill
    app.kubernetes.io/component: billing
    app.kubernetes.io/part-of: enclii
    enclii.dev/managed-by: switchyard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: waybill
  template:
    metadata:
      labels:
        app: waybill
        app.kubernetes.io/name: waybill
        app.kubernetes.io/component: billing
        app.kubernetes.io/part-of: enclii
        enclii.dev/managed-by: switchyard
    spec:
      containers:
        - name: waybill-aggregator
          image: ghcr.io/madfam-org/enclii/waybill:1ead1b30fdb4732051596d2d2ca7726dde4acf7c
          imagePullPolicy: Always
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: enclii-secrets
                  key: database-url
          ports:
            - containerPort: 4290
              name: metrics
              protocol: TCP
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          startupProbe:
            tcpSocket:
              port: 4290
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 12
          readinessProbe:
            tcpSocket:
              port: 4290
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: 4290
            initialDelaySeconds: 15
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
