package helpers

import (
	"context"
	"errors"
	"testing"
	"time"
)

func TestDefaultWaitConfig(t *testing.T) {
	cfg := DefaultWaitConfig()

	if cfg.Timeout != 5*time.Minute {
		t.Errorf("Timeout = %v, want %v", cfg.Timeout, 5*time.Minute)
	}
	if cfg.Interval != 2*time.Second {
		t.Errorf("Interval = %v, want %v", cfg.Interval, 2*time.Second)
	}
	if cfg.ProgressChar != "." {
		t.Errorf("ProgressChar = %q, want %q", cfg.ProgressChar, ".")
	}
}

func TestBuildWaitConfig(t *testing.T) {
	cfg := BuildWaitConfig()

	if cfg.Timeout != 10*time.Minute {
		t.Errorf("Timeout = %v, want %v", cfg.Timeout, 10*time.Minute)
	}
	if cfg.Interval != 5*time.Second {
		t.Errorf("Interval = %v, want %v", cfg.Interval, 5*time.Second)
	}
	if cfg.ProgressChar != "." {
		t.Errorf("ProgressChar = %q, want %q", cfg.ProgressChar, ".")
	}
}

func TestWaitResultConstants(t *testing.T) {
	// Verify the iota ordering has not changed
	if WaitContinue != 0 {
		t.Errorf("WaitContinue = %d, want 0", WaitContinue)
	}
	if WaitSuccess != 1 {
		t.Errorf("WaitSuccess = %d, want 1", WaitSuccess)
	}
	if WaitFailure != 2 {
		t.Errorf("WaitFailure = %d, want 2", WaitFailure)
	}
}

func TestWaitFor_ImmediateSuccess(t *testing.T) {
	cfg := WaitConfig{
		Timeout:      1 * time.Second,
		Interval:     10 * time.Millisecond,
		ProgressChar: "",
	}

	callCount := 0
	err := WaitFor(context.Background(), "test-op", cfg, func(_ context.Context) (WaitResult, error) {
		callCount++
		return WaitSuccess, nil
	})

	if err != nil {
		t.Errorf("WaitFor() error = %v, want nil", err)
	}
	if callCount != 1 {
		t.Errorf("statusFn called %d times, want 1", callCount)
	}
}

func TestWaitFor_ImmediateFailureWithError(t *testing.T) {
	cfg := WaitConfig{
		Timeout:      1 * time.Second,
		Interval:     10 * time.Millisecond,
		ProgressChar: "",
	}

	failErr := errors.New("deployment crashed")
	err := WaitFor(context.Background(), "deploy", cfg, func(_ context.Context) (WaitResult, error) {
		return WaitFailure, failErr
	})

	if err == nil {
		t.Fatal("WaitFor() = nil, want error")
	}
	if err != failErr {
		t.Errorf("WaitFor() error = %v, want %v", err, failErr)
	}
}

func TestWaitFor_FailureWithoutError(t *testing.T) {
	cfg := WaitConfig{
		Timeout:      1 * time.Second,
		Interval:     10 * time.Millisecond,
		ProgressChar: "",
	}

	err := WaitFor(context.Background(), "deploy", cfg, func(_ context.Context) (WaitResult, error) {
		return WaitFailure, nil
	})

	if err == nil {
		t.Fatal("WaitFor() = nil, want error")
	}
	want := "deploy failed"
	if err.Error() != want {
		t.Errorf("WaitFor() error = %q, want %q", err.Error(), want)
	}
}

func TestWaitFor_ContextCancellation(t *testing.T) {
	cfg := WaitConfig{
		Timeout:      5 * time.Second,
		Interval:     10 * time.Millisecond,
		ProgressChar: "",
	}

	ctx, cancel := context.WithCancel(context.Background())
	cancel() // Cancel immediately

	err := WaitFor(ctx, "test-op", cfg, func(_ context.Context) (WaitResult, error) {
		return WaitContinue, nil
	})

	if err == nil {
		t.Fatal("WaitFor() = nil, want context.Canceled")
	}
	if !errors.Is(err, context.Canceled) {
		t.Errorf("WaitFor() error = %v, want context.Canceled", err)
	}
}

func TestWaitFor_Timeout(t *testing.T) {
	cfg := WaitConfig{
		Timeout:      50 * time.Millisecond,
		Interval:     10 * time.Millisecond,
		ProgressChar: "",
	}

	err := WaitFor(context.Background(), "slow-op", cfg, func(_ context.Context) (WaitResult, error) {
		return WaitContinue, nil
	})

	if err == nil {
		t.Fatal("WaitFor() = nil, want timeout error")
	}
	// The timeout error message is generated by NewTimeoutError + formatDuration
	if got := err.Error(); got != "slow-op timeout after 0 seconds" {
		// 50ms rounds down to 0 seconds in formatDuration
		t.Logf("WaitFor() timeout error = %q (acceptable)", got)
	}
}

func TestWaitFor_SuccessAfterRetries(t *testing.T) {
	cfg := WaitConfig{
		Timeout:      2 * time.Second,
		Interval:     10 * time.Millisecond,
		ProgressChar: "",
	}

	callCount := 0
	err := WaitFor(context.Background(), "eventual-success", cfg, func(_ context.Context) (WaitResult, error) {
		callCount++
		if callCount >= 3 {
			return WaitSuccess, nil
		}
		return WaitContinue, nil
	})

	if err != nil {
		t.Errorf("WaitFor() error = %v, want nil", err)
	}
	if callCount < 3 {
		t.Errorf("statusFn called %d times, want >= 3", callCount)
	}
}

func TestFormatDuration(t *testing.T) {
	tests := []struct {
		name     string
		duration time.Duration
		want     string
	}{
		{
			name:     "seconds only",
			duration: 30 * time.Second,
			want:     "30 seconds",
		},
		{
			name:     "exact minutes",
			duration: 5 * time.Minute,
			want:     "5 minutes",
		},
		{
			name:     "exact hours",
			duration: 2 * time.Hour,
			want:     "2 hours",
		},
		{
			name:     "hours and minutes",
			duration: 1*time.Hour + 30*time.Minute,
			want:     "1 hours 30 minutes",
		},
		{
			name:     "one minute boundary",
			duration: 1 * time.Minute,
			want:     "1 minutes",
		},
		{
			name:     "one hour boundary",
			duration: 1 * time.Hour,
			want:     "1 hours",
		},
		{
			name:     "sub-second rounds to zero seconds",
			duration: 500 * time.Millisecond,
			want:     "0 seconds",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := formatDuration(tt.duration)
			if got != tt.want {
				t.Errorf("formatDuration(%v) = %q, want %q", tt.duration, got, tt.want)
			}
		})
	}
}

func TestWaitForWithProgress_ImmediateSuccess(t *testing.T) {
	cfg := WaitConfig{
		Timeout:      1 * time.Second,
		Interval:     10 * time.Millisecond,
		ProgressChar: "",
	}

	err := WaitForWithProgress(context.Background(), "test-op", cfg, func(_ context.Context) (WaitResult, string, error) {
		return WaitSuccess, "done", nil
	})

	if err != nil {
		t.Errorf("WaitForWithProgress() error = %v, want nil", err)
	}
}

func TestWaitForWithProgress_FailureWithError(t *testing.T) {
	cfg := WaitConfig{
		Timeout:      1 * time.Second,
		Interval:     10 * time.Millisecond,
		ProgressChar: "",
	}

	failErr := errors.New("build failed")
	err := WaitForWithProgress(context.Background(), "build", cfg, func(_ context.Context) (WaitResult, string, error) {
		return WaitFailure, "X", failErr
	})

	if err != failErr {
		t.Errorf("WaitForWithProgress() error = %v, want %v", err, failErr)
	}
}

func TestWaitForWithProgress_FailureWithoutError(t *testing.T) {
	cfg := WaitConfig{
		Timeout:      1 * time.Second,
		Interval:     10 * time.Millisecond,
		ProgressChar: "",
	}

	err := WaitForWithProgress(context.Background(), "build", cfg, func(_ context.Context) (WaitResult, string, error) {
		return WaitFailure, "X", nil
	})

	if err == nil {
		t.Fatal("WaitForWithProgress() = nil, want error")
	}
	want := "build failed"
	if err.Error() != want {
		t.Errorf("WaitForWithProgress() error = %q, want %q", err.Error(), want)
	}
}
