# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-04-18T08:11:24+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Any
from uuid import UUID

from pydantic import AnyUrl, AwareDatetime, BaseModel, EmailStr, Field


class HealthResponse(BaseModel):
    status: str | None = Field(None, examples=["ok"])
    version: str | None = Field(None, examples=["1.0.0"])
    uptime: int | None = Field(None, description="Uptime in seconds")


class LoginRequest(BaseModel):
    email: EmailStr
    password: str = Field(..., min_length=8)


class RegisterRequest(BaseModel):
    email: EmailStr
    password: str = Field(..., min_length=8)
    name: str


class RefreshRequest(BaseModel):
    refresh_token: str


class RefreshResponse(BaseModel):
    access_token: str | None = None
    expires_at: AwareDatetime | None = None
    token_type: str | None = None


class Role(StrEnum):
    admin = "admin"
    developer = "developer"
    viewer = "viewer"


class User(BaseModel):
    id: UUID | None = None
    email: EmailStr | None = None
    name: str | None = None
    role: Role | None = None


class Project(BaseModel):
    id: UUID | None = None
    name: str | None = None
    slug: str | None = None
    created_at: AwareDatetime | None = None
    updated_at: AwareDatetime | None = None


class CreateProjectRequest(BaseModel):
    name: str = Field(..., max_length=100, min_length=1)
    slug: str = Field(..., max_length=50, min_length=2, pattern="^[a-z0-9-]+$")


class Type(StrEnum):
    dev = "dev"
    staging = "staging"
    prod = "prod"


class Environment(BaseModel):
    id: UUID | None = None
    name: str | None = None
    type: Type | None = None
    project_id: UUID | None = None
    created_at: AwareDatetime | None = None


class CreateEnvironmentRequest(BaseModel):
    name: str
    type: Type


class Status(StrEnum):
    running = "running"
    stopped = "stopped"
    building = "building"


class Type2(StrEnum):
    auto = "auto"
    dockerfile = "dockerfile"
    buildpack = "buildpack"


class BuildConfig(BaseModel):
    type: Type2 | None = None
    dockerfile: str | None = None
    buildpack: str | None = None


class CreateServiceRequest(BaseModel):
    name: str
    git_repo: str
    app_path: str | None = None
    auto_deploy: bool | None = True
    auto_deploy_branch: str | None = "main"
    build_config: BuildConfig | None = None
    headers: dict[str, str] | None = Field(
        None,
        description="Custom HTTP response headers injected via nginx ingress annotations",
    )


class UpdateServiceRequest(BaseModel):
    name: str | None = None
    git_repo: str | None = None
    app_path: str | None = None
    auto_deploy: bool | None = None
    auto_deploy_branch: str | None = None
    auto_deploy_env: str | None = None
    build_config: BuildConfig | None = None
    headers: dict[str, str] | None = Field(
        None,
        description="Custom HTTP response headers injected via nginx ingress annotations",
    )


class Service1(BaseModel):
    name: str
    app_path: str
    port: int | None = None
    build_command: str | None = None
    start_command: str | None = None
    auto_deploy: bool | None = True
    auto_deploy_branch: str | None = None
    auto_deploy_env: str | None = None


class BulkCreateServicesRequest(BaseModel):
    git_repo: str
    git_branch: str | None = "main"
    services: list[Service1]


class Status1(StrEnum):
    running = "running"
    stopped = "stopped"
    building = "building"
    failed = "failed"


class Health(StrEnum):
    healthy = "healthy"
    unhealthy = "unhealthy"
    unknown = "unknown"


class ServiceStatus(BaseModel):
    service_id: UUID | None = None
    status: Status1 | None = None
    health: Health | None = None
    replicas: int | None = None
    ready_replicas: int | None = None
    pod_count: int | None = None


class HealthCheckConfig(BaseModel):
    path: str | None = "/health"
    port: int | None = None
    liveness_path: str | None = None
    readiness_path: str | None = None
    initial_delay_seconds: int | None = 10
    period_seconds: int | None = 10
    timeout_seconds: int | None = 5
    failure_threshold: int | None = 3
    disabled: bool | None = False


class ResourceConfig(BaseModel):
    cpu_request: str | None = Field(None, examples=["100m"])
    cpu_limit: str | None = Field(None, examples=["500m"])
    memory_request: str | None = Field(None, examples=["128Mi"])
    memory_limit: str | None = Field(None, examples=["512Mi"])


class Route(BaseModel):
    path: str | None = None
    port: int | None = None


class BuildRequest(BaseModel):
    git_sha: str
    git_branch: str | None = None


class Status2(StrEnum):
    building = "building"
    ready = "ready"
    failed = "failed"


class Release(BaseModel):
    id: UUID | None = None
    service_id: UUID | None = None
    version: str | None = None
    image_uri: str | None = None
    git_sha: str | None = None
    status: Status2 | None = None
    created_at: AwareDatetime | None = None
    updated_at: AwareDatetime | None = None


class Strategy(StrEnum):
    blue_green = "blue-green"
    canary = "canary"
    rolling = "rolling"


class DeployRequest(BaseModel):
    release_id: UUID
    strategy: Strategy | None = "rolling"


class Status3(StrEnum):
    pending = "pending"
    deploying = "deploying"
    running = "running"
    failed = "failed"
    cancelled = "cancelled"


class Deployment(BaseModel):
    id: UUID | None = None
    release_id: UUID | None = None
    environment_id: UUID | None = None
    service_id: UUID | None = None
    strategy: Strategy | None = "rolling"
    status: Status3 | None = None
    replicas: int | None = None
    ready_replicas: int | None = None
    created_at: AwareDatetime | None = None
    updated_at: AwareDatetime | None = None


class LogEntry(BaseModel):
    timestamp: AwareDatetime | None = None
    pod: str | None = None
    container: str | None = None
    message: str | None = None
    level: str | None = None


class TlsProvider(StrEnum):
    letsencrypt = "letsencrypt"
    cloudflare = "cloudflare"


class CustomDomain(BaseModel):
    id: UUID | None = None
    service_id: UUID | None = None
    environment_id: UUID | None = None
    domain: str | None = None
    is_platform_domain: bool | None = None
    verified: bool | None = None
    verification_txt: str | None = None
    dns_cname: str | None = None
    tls_enabled: bool | None = None
    tls_provider: TlsProvider | None = None
    zero_trust_enabled: bool | None = None
    verified_at: AwareDatetime | None = None
    created_at: AwareDatetime | None = None


class DomainsListResponse(BaseModel):
    domains: list[CustomDomain] | None = None
    count: int | None = None


class EnvVar(BaseModel):
    id: UUID | None = None
    service_id: UUID | None = None
    name: str | None = None
    value: str | None = Field(None, description="Masked if is_secret is true")
    is_secret: bool | None = None
    created_at: AwareDatetime | None = None
    updated_at: AwareDatetime | None = None


class CreateEnvVarRequest(BaseModel):
    name: str
    value: str
    is_secret: bool | None = False


class Status4(StrEnum):
    pending = "pending"
    building = "building"
    deploying = "deploying"
    active = "active"
    sleeping = "sleeping"
    failed = "failed"
    closed = "closed"


class PreviewEnvironment(BaseModel):
    id: UUID | None = None
    service_id: UUID | None = None
    pr_number: int | None = None
    pr_title: str | None = None
    pr_url: str | None = None
    pr_author: str | None = None
    pr_branch: str | None = None
    pr_base_branch: str | None = None
    commit_sha: str | None = None
    status: Status4 | None = None
    url: str | None = None
    created_at: AwareDatetime | None = None
    updated_at: AwareDatetime | None = None
    closed_at: AwareDatetime | None = None


class CreatePreviewRequest(BaseModel):
    service_id: UUID
    pr_number: int
    pr_title: str | None = None
    pr_url: str | None = None
    pr_author: str | None = None
    pr_branch: str
    pr_base_branch: str | None = None
    commit_sha: str


class PreviewComment(BaseModel):
    id: UUID | None = None
    preview_id: UUID | None = None
    author_id: UUID | None = None
    author_name: str | None = None
    content: str | None = None
    resolved: bool | None = None
    created_at: AwareDatetime | None = None


class CreatePreviewCommentRequest(BaseModel):
    content: str


class Node(BaseModel):
    id: UUID | None = None
    name: str | None = None
    type: str | None = None


class Edge(BaseModel):
    from_: UUID | None = Field(None, alias="from")
    to: UUID | None = None


class Topology(BaseModel):
    nodes: list[Node] | None = None
    edges: list[Edge] | None = None


class Strategy2(StrEnum):
    parallel = "parallel"
    sequential = "sequential"
    dependency_ordered = "dependency_ordered"


class CreateDeploymentGroupRequest(BaseModel):
    service_ids: list[UUID] | None = Field(
        None, description="Service IDs to include (all services if empty)"
    )
    strategy: Strategy2 | None = "dependency_ordered"
    git_sha: str | None = None
    pr_url: str | None = None


class DeploymentGroup(BaseModel):
    id: UUID | None = None
    project_id: UUID | None = None
    environment_id: UUID | None = None
    strategy: str | None = None
    status: str | None = None
    deployments: list[Deployment] | None = None
    created_at: AwareDatetime | None = None


class DeploymentGroupResponse(BaseModel):
    group: DeploymentGroup | None = None
    deployment_order: list[list[UUID]] | None = None
    layers_count: int | None = None


class UserRole(StrEnum):
    owner = "owner"
    admin = "admin"
    member = "member"
    viewer = "viewer"


class Team(BaseModel):
    id: UUID | None = None
    name: str | None = None
    slug: str | None = None
    description: str | None = None
    avatar_url: str | None = None
    billing_email: str | None = None
    member_count: int | None = None
    user_role: UserRole | None = None
    created_at: AwareDatetime | None = None
    updated_at: AwareDatetime | None = None


class CreateTeamRequest(BaseModel):
    name: str = Field(..., max_length=100, min_length=2)
    slug: str = Field(..., max_length=50, min_length=2, pattern="^[a-z0-9-]+$")
    description: str | None = None
    billing_email: EmailStr | None = None


class UpdateTeamRequest(BaseModel):
    name: str | None = None
    description: str | None = None
    billing_email: EmailStr | None = None
    avatar_url: str | None = None


class Role1(StrEnum):
    owner = "owner"
    admin = "admin"
    member = "member"
    viewer = "viewer"


class TeamMember(BaseModel):
    id: UUID | None = None
    user_id: UUID | None = None
    email: str | None = None
    name: str | None = None
    role: Role1 | None = None
    joined_at: AwareDatetime | None = None


class TeamInvitation(BaseModel):
    id: UUID | None = None
    email: str | None = None
    role: str | None = None
    token: str | None = None
    expires_at: AwareDatetime | None = None
    created_at: AwareDatetime | None = None


class Role2(StrEnum):
    admin = "admin"
    member = "member"
    viewer = "viewer"


class InviteMemberRequest(BaseModel):
    email: EmailStr
    role: Role2


class InvitationDetails(BaseModel):
    id: UUID | None = None
    team: Team | None = None
    email: str | None = None
    role: str | None = None
    inviter_name: str | None = None
    expires_at: AwareDatetime | None = None


class UsageSummary(BaseModel):
    compute_hours: float | None = None
    storage_gb: float | None = None
    bandwidth_gb: float | None = None
    build_minutes: float | None = None
    period_start: AwareDatetime | None = None
    period_end: AwareDatetime | None = None


class CostBreakdown(BaseModel):
    total: float | None = None
    by_service: dict[str, float] | None = None
    by_resource: dict[str, float] | None = None
    period: str | None = None


class Activity(BaseModel):
    id: UUID | None = None
    action: str | None = None
    resource_type: str | None = None
    resource_id: UUID | None = None
    actor_id: UUID | None = None
    actor_name: str | None = None
    details: dict[str, Any] | None = None
    created_at: AwareDatetime | None = None


class ActivityListResponse(BaseModel):
    activities: list[Activity] | None = None
    count: int | None = None
    limit: int | None = None
    offset: int | None = None


class MetricsSnapshot(BaseModel):
    timestamp: AwareDatetime | None = None
    cpu_usage: float | None = None
    memory_usage: float | None = None
    network_in: float | None = None
    network_out: float | None = None
    requests_per_second: float | None = None
    error_rate: float | None = None


class Service2(BaseModel):
    id: UUID | None = None
    name: str | None = None
    health: Health | None = None
    last_check: AwareDatetime | None = None


class ServiceHealthResponse(BaseModel):
    services: list[Service2] | None = None


class Error(BaseModel):
    timestamp: AwareDatetime | None = None
    service: str | None = None
    message: str | None = None
    stack_trace: str | None = None
    count: int | None = None


class RecentErrorsResponse(BaseModel):
    errors: list[Error] | None = None


class Severity(StrEnum):
    critical = "critical"
    warning = "warning"
    info = "info"


class Alert(BaseModel):
    id: str | None = None
    severity: Severity | None = None
    message: str | None = None
    service: str | None = None
    started_at: AwareDatetime | None = None


class IntegrationStatusResponse(BaseModel):
    connected: bool | None = None
    username: str | None = None
    avatar_url: str | None = None
    connected_at: AwareDatetime | None = None


class Repo(BaseModel):
    owner: str | None = None
    name: str | None = None
    full_name: str | None = None
    private: bool | None = None
    default_branch: str | None = None


class GitHubReposResponse(BaseModel):
    repos: list[Repo] | None = None
    count: int | None = None


class DetectedService(BaseModel):
    name: str | None = None
    path: str | None = None
    type: str | None = None
    port: int | None = None


class RepositoryAnalysis(BaseModel):
    detected_services: list[DetectedService] | None = None
    build_config: BuildConfig | None = None
    is_monorepo: bool | None = None


class ApiToken(BaseModel):
    id: UUID | None = None
    name: str | None = None
    prefix: str | None = Field(None, description="First 8 characters of token for identification")
    created_at: AwareDatetime | None = None
    expires_at: AwareDatetime | None = None
    last_used_at: AwareDatetime | None = None


class Type3(StrEnum):
    k3s = "k3s"
    k8s = "k8s"
    vcluster = "vcluster"


class Status5(StrEnum):
    pending = "pending"
    ready = "ready"
    degraded = "degraded"
    offline = "offline"
    deleting = "deleting"


class Cluster(BaseModel):
    id: UUID | None = None
    name: str | None = None
    slug: str | None = None
    type: Type3 | None = None
    endpoint: str | None = None
    kubeconfig_secret_ref: str | None = None
    region: str | None = None
    status: Status5 | None = None
    metadata: dict[str, Any] | None = None
    created_at: AwareDatetime | None = None
    updated_at: AwareDatetime | None = None


class State(StrEnum):
    discovered = "discovered"
    inspecting = "inspecting"
    available = "available"
    provisioning = "provisioning"
    provisioned = "provisioned"
    deprovisioning = "deprovisioning"
    error = "error"


class PowerState(StrEnum):
    on = "on"
    off = "off"
    unknown = "unknown"


class BareMetalHost(BaseModel):
    id: UUID | None = None
    name: str | None = None
    cluster_id: UUID | None = None
    bmc_address: str | None = None
    bmc_credentials_ref: str | None = None
    mac_address: str | None = None
    boot_mode: str | None = None
    state: State | None = None
    power_state: PowerState | None = None
    hardware_profile: dict[str, Any] | None = None
    firmware_version: str | None = None
    root_device_hints: dict[str, Any] | None = None
    raid_config: dict[str, Any] | None = None
    cost_per_hour_cents: int | None = None
    created_at: AwareDatetime | None = None
    updated_at: AwareDatetime | None = None


class ManagementPolicy(StrEnum):
    full_control = "FullControl"
    observe_only = "ObserveOnly"
    orphan_on_delete = "OrphanOnDelete"


class SyncStatus(StrEnum):
    synced = "Synced"
    out_of_sync = "OutOfSync"
    unknown = "Unknown"
    error = "Error"


class ManagedResource(BaseModel):
    id: UUID | None = None
    name: str | None = None
    api_version: str | None = None
    kind: str | None = None
    provider: str | None = None
    cluster_id: UUID | None = None
    management_policy: ManagementPolicy | None = None
    sync_status: SyncStatus | None = None
    conditions: dict[str, Any] | None = None
    spec_hash: str | None = None
    metadata: dict[str, Any] | None = None
    created_at: AwareDatetime | None = None
    updated_at: AwareDatetime | None = None


class Status6(StrEnum):
    pending = "pending"
    creating = "creating"
    running = "running"
    paused = "paused"
    deleting = "deleting"
    error = "error"


class VirtualCluster(BaseModel):
    id: UUID | None = None
    name: str | None = None
    host_cluster_id: UUID | None = None
    tenant_id: str | None = None
    namespace: str | None = None
    k8s_version: str | None = None
    status: Status6 | None = None
    helm_release_name: str | None = None
    resource_quota: dict[str, Any] | None = None
    created_at: AwareDatetime | None = None
    updated_at: AwareDatetime | None = None


class PlacementStrategy(StrEnum):
    spread = "Spread"
    binpack = "Binpack"
    gpu_affinity = "GPUAffinity"


class PropagationPolicy(BaseModel):
    id: UUID | None = None
    name: str | None = None
    cluster_ids: list[UUID] | None = None
    resource_selectors: dict[str, Any] | None = None
    placement_strategy: PlacementStrategy | None = None
    gpu_required: bool | None = None
    priority: int | None = None
    created_at: AwareDatetime | None = None
    updated_at: AwareDatetime | None = None


class Source(StrEnum):
    argocd = "argocd"
    crossplane = "crossplane"
    manual = "manual"


class Severity1(StrEnum):
    low = "low"
    medium = "medium"
    high = "high"
    critical = "critical"


class DriftEvent(BaseModel):
    id: UUID | None = None
    source: Source | None = None
    resource_type: str | None = None
    resource_name: str | None = None
    cluster_id: UUID | None = None
    drift_details: dict[str, Any] | None = None
    severity: Severity1 | None = None
    resolved: bool | None = None
    resolved_at: AwareDatetime | None = None
    detected_at: AwareDatetime | None = None
    created_at: AwareDatetime | None = None


class CostAllocation(BaseModel):
    id: UUID | None = None
    bare_metal_host_id: UUID | None = None
    tenant_id: str | None = None
    allocation_percent: float | None = Field(None, ge=0.0, le=100.0)
    period_start: AwareDatetime | None = None
    period_end: AwareDatetime | None = None
    cost_cents: int | None = None
    created_at: AwareDatetime | None = None


class EventType(StrEnum):
    push_received = "push_received"
    build_started = "build_started"
    build_succeeded = "build_succeeded"
    build_failed = "build_failed"
    image_pushed = "image_pushed"
    digest_committed = "digest_committed"
    deploy_started = "deploy_started"
    deploy_synced = "deploy_synced"
    deploy_healthy = "deploy_healthy"
    deploy_degraded = "deploy_degraded"
    deploy_failed = "deploy_failed"
    preview_created = "preview_created"
    preview_destroyed = "preview_destroyed"


class Source1(StrEnum):
    github_webhook = "github_webhook"
    ci_callback = "ci_callback"
    argocd_callback = "argocd_callback"
    manual = "manual"


class DeploymentLifecycleEvent(BaseModel):
    id: UUID | None = None
    deployment_id: UUID | None = None
    release_id: UUID | None = None
    ci_run_id: UUID | None = None
    project_id: UUID | None = None
    service_id: UUID | None = None
    repo_full_name: str | None = None
    commit_sha: str | None = None
    branch: str | None = None
    ref: str | None = None
    target_env: str | None = None
    event_type: EventType | None = None
    source: Source1 | None = None
    message: str | None = None
    metadata: dict[str, Any] | None = None
    created_at: AwareDatetime | None = None


class LifecycleEventCreate(BaseModel):
    repo_full_name: str
    commit_sha: str
    branch: str
    ref: str
    event_type: str
    source: str
    target_env: str | None = None
    message: str | None = None
    metadata: dict[str, Any] | None = None


class PostgresProvisionSpec(BaseModel):
    database_name: str = Field(..., pattern="^[a-z][a-z0-9_]{0,62}$")
    role_name: str | None = Field(None, description="Defaults to database_name")
    role_password: str
    extensions: list[str] | None = None


class SecretEntry(BaseModel):
    key: str
    value: str


class R2ProvisionSpec(BaseModel):
    bucket_name: str


class ProvisionPostgresRequest(BaseModel):
    namespace: str
    spec: PostgresProvisionSpec


class ProvisionSecretsRequest(BaseModel):
    namespace: str
    secrets: list[SecretEntry]


class ProvisionR2Request(BaseModel):
    namespace: str
    bucket_name: str


class OnboardStatus(StrEnum):
    pending = "pending"
    in_progress = "in_progress"
    completed = "completed"
    partial = "partial"
    failed = "failed"


class OnboardingRegistration(BaseModel):
    id: UUID | None = None
    project_id: UUID | None = None
    repo_full_name: str | None = None
    webhook_id: int | None = None
    argocd_app_name: str | None = None
    onboard_status: OnboardStatus | None = None
    error_message: str | None = None
    created_at: AwareDatetime | None = None
    updated_at: AwareDatetime | None = None


class PreflightIssue(BaseModel):
    file: str | None = Field(None, description="Manifest filename")
    kind: str | None = Field(None, description="K8s resource kind (e.g. Deployment, Service)")
    name: str | None = Field(None, description="Resource name from metadata")
    message: str | None = Field(None, description="Validation error or policy violation message")


class StatusServiceEntry(BaseModel):
    name: str | None = None
    url: str | None = None
    group: str | None = None
    description: str | None = None


class ExecRequest(BaseModel):
    command: list[str] = Field(
        ...,
        description="Command to execute (must match allowlist)",
        examples=[["python", "manage.py", "migrate"]],
    )
    timeout: int | None = Field(
        60, description="Timeout in seconds (default 60, max 1800)", le=1800
    )
    env: str | None = Field("production", description="Target environment")


class ExecResponse(BaseModel):
    stdout: str | None = Field(None, description="Standard output from command")
    stderr: str | None = Field(None, description="Standard error from command")
    exit_code: int | None = Field(None, description="Exit code (0 = success)")
    pod: str | None = Field(None, description="Pod name where command was executed")
    duration_ms: int | None = Field(None, description="Execution duration in milliseconds")


class RestartRequest(BaseModel):
    env: str | None = Field("production", description="Target environment")
    reason: str | None = Field("manual-restart", description="Audit reason for restart")


class ScaleRequest(BaseModel):
    replicas: int = Field(..., description="Desired replica count (0-10)", ge=0, le=10)
    env: str | None = Field("production", description="Target environment")


class MigrateRequest(BaseModel):
    command: list[str] = Field(
        ...,
        description="Migration command (must match migration allowlist)",
        examples=[["python", "manage.py", "migrate"]],
    )
    env: str | None = Field("production", description="Target environment")
    dry_run: bool | None = Field(False, description="Preview migration without applying")


class Status7(StrEnum):
    """
    Overall health classification
    """

    healthy = "healthy"
    degraded = "degraded"
    unhealthy = "unhealthy"


class PodHealth(BaseModel):
    name: str | None = None
    status: str | None = None
    ready: bool | None = None
    restarts: int | None = None
    age: str | None = None


class Error1(BaseModel):
    error: str | None = Field(None, description="Human-readable error message")
    details: str | None = Field(None, description="Additional details about the error")
    hint: str | None = Field(None, description="Troubleshooting hint")


class InstantRollbackRequest(BaseModel):
    target_deployment_id: UUID
    reason: str | None = None
    change_ticket_url: str | None = Field(None, description="Required for production environments")


class InstantRollbackResponse(BaseModel):
    message: str | None = None
    took_ms: int | None = None
    scaled_up: bool | None = None
    from_deployment_id: UUID | None = None
    to_deployment_id: UUID | None = None
    from_version: int | None = Field(
        None, description="v-number of the deployment being rolled back from"
    )
    to_version: int | None = Field(None, description="v-number of the target deployment")
    ready_replicas: int | None = None
    strategy: str | None = None
    namespace: str | None = None


class CanaryStartRequest(BaseModel):
    digest: str = Field(..., description="Image digest of the candidate (must already be built)")
    percentage: int = Field(..., ge=5, le=50)
    validation_window_minutes: int | None = Field(None, ge=1, le=60)
    smoke_endpoint: str | None = None
    error_rate_threshold: float | None = Field(None, ge=0.0, le=0.5)
    environment_name: str | None = None
    change_ticket_url: str | None = None
    total_replicas: int | None = None


class CanaryRolloutState(StrEnum):
    pending = "pending"
    running = "running"
    validating = "validating"
    promoting = "promoting"
    succeeded = "succeeded"
    auto_rolled_back = "auto_rolled_back"
    manual_rolled_back = "manual_rolled_back"
    failed = "failed"


class CanaryRolloutResponse(BaseModel):
    id: UUID | None = None
    service_id: UUID | None = None
    environment_id: UUID | None = None
    stable_deployment_id: UUID | None = None
    canary_deployment_id: UUID | None = None
    new_stable_deployment_id: UUID | None = None
    canary_digest: str | None = None
    canary_percentage: int | None = None
    total_replicas: int | None = None
    canary_replicas: int | None = None
    stable_replicas: int | None = None
    validation_window_seconds: int | None = None
    smoke_endpoint: str | None = None
    error_rate_threshold: float | None = None
    state: CanaryRolloutState | None = None
    started_at: AwareDatetime | None = None
    validating_started_at: AwareDatetime | None = None
    promoting_started_at: AwareDatetime | None = None
    terminal_at: AwareDatetime | None = None
    change_ticket_url: str | None = None
    last_error: str | None = None
    rollback_reason: str | None = None
    actual_percentage: float | None = Field(
        None, description="Computed percentage (canary_replicas / total_replicas)"
    )
    created_at: AwareDatetime | None = None
    updated_at: AwareDatetime | None = None


class OutboundWebhookEventType(StrEnum):
    deploy_started = "deploy.started"
    deploy_succeeded = "deploy.succeeded"
    deploy_failed = "deploy.failed"
    rollback_succeeded = "rollback.succeeded"
    secret_rotated = "secret.rotated"
    service_scaled = "service.scaled"


class OutboundWebhookSubscription(BaseModel):
    id: UUID | None = None
    project_id: UUID | None = None
    name: str | None = None
    url: AnyUrl | None = Field(None, description="Must be https://")
    secret_sha256_prefix: str | None = Field(
        None,
        description="First 8 chars of SHA-256(secret) for identifying which secret is active",
    )
    event_types: list[OutboundWebhookEventType] | None = Field(
        None, description="Empty array = subscribe to all event types"
    )
    active: bool | None = None
    created_by: str | None = None
    created_at: AwareDatetime | None = None
    updated_at: AwareDatetime | None = None
    last_success_at: AwareDatetime | None = None
    last_failure_at: AwareDatetime | None = None
    consecutive_failures: int | None = None
    auto_disabled_at: AwareDatetime | None = None


class OutboundWebhookSubscriptionCreateRequest(BaseModel):
    name: str
    url: AnyUrl = Field(..., description="Must be https://")
    event_types: list[OutboundWebhookEventType] | None = None


class OutboundWebhookSubscriptionUpdateRequest(BaseModel):
    """
    Only non-null fields are applied
    """

    name: str | None = None
    url: AnyUrl | None = None
    event_types: list[OutboundWebhookEventType] | None = None
    active: bool | None = None


class OutboundWebhookSubscriptionCreateResponse(BaseModel):
    subscription: OutboundWebhookSubscription | None = None
    signing_secret: str | None = Field(
        None,
        description="Raw signing secret — returned exactly once. Server only stores a\nSHA-256 hash. Caller must persist immediately.\n",
    )
    note: str | None = None


class OutboundWebhookDeliveryStatus(StrEnum):
    pending = "pending"
    delivering = "delivering"
    delivered = "delivered"
    failed = "failed"
    dlq = "dlq"


class OutboundWebhookDelivery(BaseModel):
    id: UUID | None = None
    subscription_id: UUID | None = None
    lifecycle_event_id: UUID | None = None
    event_id: str | None = None
    event_type: OutboundWebhookEventType | None = None
    payload: dict[str, Any] | None = None
    payload_sha256: str | None = None
    attempt_number: int | None = None
    status: OutboundWebhookDeliveryStatus | None = None
    http_status: int | None = None
    response_snippet: str | None = None
    error_message: str | None = None
    attempted_at: AwareDatetime | None = None
    delivered_at: AwareDatetime | None = None
    duration_ms: int | None = None
    next_retry_at: AwareDatetime | None = None
    created_at: AwareDatetime | None = None


class DashboardStats(BaseModel):
    healthy_services: int | None = None
    deployments_today: int | None = None
    active_projects: int | None = None
    recent_activity: list[Activity] | None = None


class LoginResponse(BaseModel):
    user: User | None = None
    access_token: str | None = None
    refresh_token: str | None = None
    expires_at: AwareDatetime | None = None
    token_type: str | None = "Bearer"
    idp_token: str | None = Field(None, description="IDP OAuth token (OIDC mode only)")
    idp_token_expires_at: AwareDatetime | None = None


class Service(BaseModel):
    id: UUID | None = None
    project_id: UUID | None = None
    name: str | None = None
    git_repo: str | None = Field(None, description="GitHub HTTPS URL")
    git_branch: str | None = None
    app_path: str | None = Field(None, description="Path in monorepo")
    auto_deploy: bool | None = None
    auto_deploy_branch: str | None = None
    auto_deploy_env: str | None = None
    build_config: BuildConfig | None = None
    headers: dict[str, str] | None = Field(
        None,
        description="Custom HTTP response headers injected via nginx ingress annotations",
        examples=[
            {
                "Cross-Origin-Opener-Policy": "same-origin",
                "Cross-Origin-Embedder-Policy": "require-corp",
            }
        ],
    )
    status: Status | None = None
    created_at: AwareDatetime | None = None
    updated_at: AwareDatetime | None = None


class BulkCreateServicesResponse(BaseModel):
    created: int | None = None
    services: list[Service] | None = None


class ServiceSettings(BaseModel):
    id: UUID | None = None
    name: str | None = None
    health_check: HealthCheckConfig | None = None
    resources: ResourceConfig | None = None


class NetworkingConfig(BaseModel):
    routes: list[Route] | None = None
    domains: list[CustomDomain] | None = None
    tls_status: str | None = None


class AlertsResponse(BaseModel):
    critical: list[Alert] | None = None
    warning: list[Alert] | None = None
    info: list[Alert] | None = None


class OnboardingRequest(BaseModel):
    """
    Request body for repository onboarding. The onboarding pipeline executes
    these steps in order: namespace, argocd_config, network_policies,
    status_registration, registry_credentials, domain_provisioning,
    postgres, secrets, r2. Each step reports ok/failed/skipped in step_results.

    """

    repo_full_name: str = Field(..., description="GitHub owner/repo (e.g. madfam-org/my-project)")
    project_name: str = Field(..., description="Project name for Enclii registration")
    namespace: str | None = Field(None, description="K8s namespace (defaults to project_name)")
    manifest_path: str | None = Field(
        None, description="Path to K8s manifests in the repo (default k8s/production)"
    )
    branch: str | None = Field("main", description="Branch to track")
    secret_name: str | None = Field(
        None, description="K8s Secret name (default <project>-credentials)"
    )
    provision_postgres: PostgresProvisionSpec | None = None
    provision_secrets: list[SecretEntry] | None = None
    provision_r2: R2ProvisionSpec | None = None


class PreflightResult(BaseModel):
    pass_: bool | None = Field(
        None, alias="pass", description="Whether all manifests passed validation"
    )
    violations: list[PreflightIssue] | None = None


class DetailedHealthResponse(BaseModel):
    status: Status7 | None = Field(None, description="Overall health classification")
    service_name: str | None = None
    environment: str | None = None
    pods: list[PodHealth] | None = None
    total_pods: int | None = None
    ready_pods: int | None = None
    restart_count: int | None = None
    checked_at: AwareDatetime | None = None
