package api

import (
	"fmt"
	"strings"
)

// generateArgocdApp generates an ArgoCD Application YAML matching the App-of-Apps pattern.
// The generated YAML is returned to the caller to commit to infra/argocd/apps/.
func generateArgocdApp(repoURL, manifestPath, namespace, appName, branch string) string {
	if branch == "" {
		branch = "main"
	}
	if manifestPath == "" {
		manifestPath = "infra/k8s/production"
	}

	// Sanitize app name for Kubernetes metadata
	appName = strings.ToLower(appName)
	appName = strings.ReplaceAll(appName, "_", "-")

	// Extract org/repo for labels
	partOf := appName
	if idx := strings.LastIndex(appName, "-services"); idx != -1 {
		partOf = appName[:idx]
	}

	return fmt.Sprintf(`# %s Application
# Auto-generated by Enclii onboarding API
# Source: %s
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: %s
  namespace: argocd
  labels:
    app.kubernetes.io/name: %s
    app.kubernetes.io/part-of: %s
    app.kubernetes.io/managed-by: enclii-onboarding
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: %s
    targetRevision: %s
    path: %s

  destination:
    server: https://kubernetes.default.svc
    namespace: %s

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
    - group: ""
      kind: Service
      jsonPointers:
        - /spec/clusterIP
`, appName, repoURL, appName, appName, partOf, repoURL, branch, manifestPath, namespace)
}
