package api

import (
	"context"
	"database/sql"
	"fmt"
	"net/http"
	"strings"

	"github.com/gin-gonic/gin"
	k8scorev1 "k8s.io/api/core/v1"
	k8smetav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	"github.com/madfam-org/enclii/apps/switchyard-api/internal/logging"
	"github.com/madfam-org/enclii/packages/sdk-go/pkg/types"
)

// OnboardRepo handles self-service repo onboarding
// POST /v1/admin/onboard
func (h *Handler) OnboardRepo(c *gin.Context) {
	ctx := c.Request.Context()

	var req types.OnboardingRequest
	if err := c.ShouldBindJSON(&req); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	h.logger.Info(ctx, "Starting repo onboarding",
		logging.String("repo", req.RepoFullName),
		logging.String("project", req.ProjectName))

	// Check if already onboarded
	existing, err := h.repos.Onboardings.GetByRepo(ctx, req.RepoFullName)
	if err == nil && existing != nil {
		c.JSON(http.StatusConflict, gin.H{
			"error":   "Repository already onboarded",
			"status":  existing.OnboardStatus,
			"repo":    existing.RepoFullName,
			"created": existing.CreatedAt,
		})
		return
	}

	// Step 1: Validate enclii.yaml from target repo
	parts := strings.SplitN(req.RepoFullName, "/", 2)
	if len(parts) != 2 {
		c.JSON(http.StatusBadRequest, gin.H{"error": "repo_full_name must be in owner/repo format"})
		return
	}

	encliiConfig := h.fetchAndParseEncliiYAML(ctx, req.RepoFullName, "HEAD")

	// Step 2: Find or create project
	project, err := h.repos.Projects.GetBySlug(req.ProjectName)
	if err != nil {
		if err == sql.ErrNoRows {
			// Create project
			project = &types.Project{
				Name: req.ProjectName,
				Slug: req.ProjectName,
			}
			if createErr := h.repos.Projects.Create(project); createErr != nil {
				h.logger.Error(ctx, "Failed to create project during onboarding",
					logging.String("project", req.ProjectName),
					logging.Error("db_error", createErr))
				c.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to create project"})
				return
			}
			h.logger.Info(ctx, "Created project for onboarding",
				logging.String("project_id", project.ID.String()),
				logging.String("project_name", req.ProjectName))
		} else {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to look up project"})
			return
		}
	}

	// Step 3: Create service from enclii.yaml metadata if available
	var serviceNames []string
	if encliiConfig != nil && encliiConfig.Metadata.Name != "" {
		svcName := encliiConfig.Metadata.Name
		// Check if service already exists
		_, lookupErr := h.repos.Services.GetByName(svcName)
		if lookupErr == nil {
			serviceNames = append(serviceNames, svcName+" (existing)")
		} else {
			newService := &types.Service{
				ProjectID:  project.ID,
				Name:       svcName,
				GitRepo:    "https://github.com/" + req.RepoFullName,
				AutoDeploy: true,
			}
			if createErr := h.repos.Services.Create(newService); createErr != nil {
				h.logger.Warn(ctx, "Failed to create service during onboarding (non-fatal)",
					logging.String("service", svcName),
					logging.Error("db_error", createErr))
				serviceNames = append(serviceNames, svcName+" (failed)")
			} else {
				serviceNames = append(serviceNames, svcName+" (created)")
			}
		}
	}

	// Step 4: Build project config for ArgoCD ApplicationSet
	namespace := req.Namespace
	if namespace == "" {
		namespace = req.ProjectName
	}
	manifestPath := req.ManifestPath
	if manifestPath == "" {
		manifestPath = "infra/k8s/production"
	}
	branch := "main"
	if req.Branch != nil {
		branch = *req.Branch
	}
	appName := req.ProjectName + "-services"
	repoURL := "https://github.com/" + req.RepoFullName + ".git"

	// Generate config.json for the ApplicationSet generator
	projectConfig := generateProjectConfig(req.ProjectName, repoURL, branch, manifestPath, namespace)

	// Also generate the legacy YAML for the response body (informational)
	argocdYAML := generateArgocdApp(repoURL, manifestPath, namespace, appName, branch)

	// Step 5: Auto-commit config.json to infra/argocd/projects/<name>/config.json
	// The ApplicationSet auto-generates the Application CR from this file
	var argocdCommitSHA string
	var argocdCommitErr error
	if h.config.GitHubToken != "" && h.config.EncliiRepoOwner != "" && h.config.EncliiRepoName != "" {
		configFilePath := fmt.Sprintf("infra/argocd/projects/%s/config.json", req.ProjectName)
		commitMsg := fmt.Sprintf("feat(argocd): auto-onboard %s\n\nGenerated by POST /v1/admin/onboard for %s\nApplicationSet auto-generates the ArgoCD Application from this config.", req.ProjectName, req.RepoFullName)

		argocdCommitSHA, argocdCommitErr = createOrUpdateGitHubFile(
			ctx,
			h.config.GitHubToken,
			h.config.EncliiRepoOwner,
			h.config.EncliiRepoName,
			configFilePath,
			[]byte(projectConfig),
			commitMsg,
			"main",
		)
		if argocdCommitErr != nil {
			h.logger.Warn(ctx, "Failed to auto-commit project config (non-fatal, config returned in response)",
				logging.String("project", req.ProjectName),
				logging.Error("error", argocdCommitErr))
		} else {
			h.logger.Info(ctx, "Auto-committed project config to Enclii repo",
				logging.String("project", req.ProjectName),
				logging.String("commit", argocdCommitSHA))
		}
	}

	// Step 6: Ensure namespace with required labels + registry credentials
	h.ensureOnboardingNamespace(ctx, namespace)
	h.copyRegistryCredentials(ctx, namespace)

	// Step 7: Provision domains from enclii.yaml (if available)
	var domainResults []string
	if encliiConfig != nil && len(encliiConfig.Spec.Domains) > 0 {
		// Get the first service to associate domains with
		svcList, _ := h.repos.Services.ListByProject(project.ID)
		if len(svcList) > 0 {
			go h.provisionDomainsFromYAML(context.Background(), svcList[0], encliiConfig)
			for _, d := range encliiConfig.Spec.Domains {
				domainResults = append(domainResults, d.Name+" (provisioning)")
			}
		}
	}

	// Step 8: Register onboarding
	configSnapshot := map[string]interface{}{
		"manifest_path": manifestPath,
		"namespace":     namespace,
		"branch":        branch,
		"services":      serviceNames,
		"domains":       domainResults,
	}
	if encliiConfig != nil {
		configSnapshot["enclii_yaml_found"] = true
	}
	if argocdCommitSHA != "" {
		configSnapshot["argocd_commit"] = argocdCommitSHA
	}

	reg := &types.OnboardingRegistration{
		ProjectID:      project.ID,
		RepoFullName:   req.RepoFullName,
		ArgocdAppName:  &appName,
		OnboardStatus:  "completed",
		ConfigSnapshot: configSnapshot,
	}
	if err := h.repos.Onboardings.Create(ctx, reg); err != nil {
		h.logger.Error(ctx, "Failed to register onboarding",
			logging.String("repo", req.RepoFullName),
			logging.Error("db_error", err))
		// Non-fatal — continue with response
	}

	h.logger.Info(ctx, "Repo onboarding completed",
		logging.String("repo", req.RepoFullName),
		logging.String("project", req.ProjectName),
		logging.String("app_name", appName))

	// Build next_steps based on what was auto-provisioned
	nextSteps := []string{}
	if argocdCommitSHA != "" {
		nextSteps = append(nextSteps, fmt.Sprintf("1. Project config auto-committed (%s) — ApplicationSet generates ArgoCD app", argocdCommitSHA[:8]))
	} else {
		nextSteps = append(nextSteps, fmt.Sprintf("1. Commit config.json to infra/argocd/projects/%s/config.json", req.ProjectName))
	}
	nextSteps = append(nextSteps,
		"2. Ensure GitHub webhook is configured to POST to https://api.enclii.dev/v1/webhooks/github",
		"3. Push to main branch to trigger first auto-deploy",
		"4. Check lifecycle events: GET /v1/lifecycle/timeline/"+req.RepoFullName,
	)

	c.JSON(http.StatusOK, gin.H{
		"status":         "completed",
		"repo":           req.RepoFullName,
		"project":        req.ProjectName,
		"next_steps":     nextSteps,
		"argocd_yaml":    argocdYAML,
		"project_config": projectConfig,
		"argocd_app":     appName,
		"argocd_commit":  argocdCommitSHA,
		"namespace":      namespace,
		"manifest_path":  manifestPath,
		"services":       serviceNames,
		"domains":        domainResults,
	})
}

// ensureOnboardingNamespace creates the target namespace with required labels,
// or patches an existing namespace to add missing labels.
func (h *Handler) ensureOnboardingNamespace(ctx context.Context, namespace string) {
	if h.k8sClient == nil || !h.k8sClient.IsValid() {
		h.logger.Warn(ctx, "K8s client not available, skipping namespace creation",
			logging.String("namespace", namespace))
		return
	}

	if err := h.k8sClient.EnsureNamespace(ctx, namespace); err != nil {
		h.logger.Warn(ctx, "Failed to ensure onboarding namespace (non-fatal)",
			logging.String("namespace", namespace),
			logging.Error("error", err))
	} else {
		h.logger.Info(ctx, "Ensured namespace for onboarding",
			logging.String("namespace", namespace))
	}
}

// copyRegistryCredentials copies ghcr-credentials from the enclii namespace to a target namespace.
// This allows pods in the target namespace to pull images from GHCR.
func (h *Handler) copyRegistryCredentials(ctx context.Context, targetNamespace string) {
	if h.serviceReconciler == nil {
		h.logger.Warn(ctx, "Service reconciler not available, skipping credential copy",
			logging.String("namespace", targetNamespace))
		return
	}

	// The reconciler already has ensureRegistryCredentials — leverage it indirectly
	// by calling EnsureNamespace on the k8s client (which the reconciler's ensureNamespace does)
	// Since we already called ensureOnboardingNamespace above, and the reconciler's
	// ensureNamespace handles credential copying, we can use the reconciler directly
	if h.k8sClient == nil || !h.k8sClient.IsValid() {
		return
	}

	const secretName = "ghcr-credentials" // #nosec G101 -- secret reference name, not a credential
	const sourceNamespace = "enclii"

	secretClient := h.k8sClient.Clientset.CoreV1().Secrets(targetNamespace)

	// Check if secret already exists
	_, err := secretClient.Get(ctx, secretName, k8smetav1.GetOptions{})
	if err == nil {
		return // Already exists
	}

	// Get source secret
	sourceClient := h.k8sClient.Clientset.CoreV1().Secrets(sourceNamespace)
	sourceSecret, err := sourceClient.Get(ctx, secretName, k8smetav1.GetOptions{})
	if err != nil {
		h.logger.Warn(ctx, "Source registry credentials not found, skipping copy",
			logging.String("namespace", targetNamespace),
			logging.Error("error", err))
		return
	}

	// Create copy in target namespace
	newSecret := &k8scorev1.Secret{
		ObjectMeta: k8smetav1.ObjectMeta{
			Name:      secretName,
			Namespace: targetNamespace,
			Labels: map[string]string{
				"enclii.dev/managed-by":  "onboarding-api",
				"enclii.dev/copied-from": sourceNamespace,
			},
		},
		Type: sourceSecret.Type,
		Data: sourceSecret.Data,
	}

	if _, err := secretClient.Create(ctx, newSecret, k8smetav1.CreateOptions{}); err != nil {
		h.logger.Warn(ctx, "Failed to copy registry credentials (non-fatal)",
			logging.String("namespace", targetNamespace),
			logging.Error("error", err))
	} else {
		h.logger.Info(ctx, "Copied registry credentials to namespace",
			logging.String("namespace", targetNamespace))
	}
}

// ListOnboardings returns all onboarded repos
// GET /v1/admin/onboard
func (h *Handler) ListOnboardings(c *gin.Context) {
	ctx := c.Request.Context()

	regs, err := h.repos.Onboardings.List(ctx)
	if err != nil {
		h.logger.Error(ctx, "Failed to list onboardings",
			logging.Error("db_error", err))
		c.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to list onboardings"})
		return
	}

	c.JSON(http.StatusOK, gin.H{
		"count":         len(regs),
		"registrations": regs,
	})
}

// GetOnboarding returns a specific repo's onboarding status
// GET /v1/admin/onboard/:owner/:repo
func (h *Handler) GetOnboarding(c *gin.Context) {
	ctx := c.Request.Context()

	owner := c.Param("owner")
	repo := c.Param("repo")
	repoFullName := owner + "/" + repo

	reg, err := h.repos.Onboardings.GetByRepo(ctx, repoFullName)
	if err != nil {
		if err == sql.ErrNoRows {
			c.JSON(http.StatusNotFound, gin.H{"error": "Repository not onboarded"})
			return
		}
		h.logger.Error(ctx, "Failed to get onboarding",
			logging.String("repo", repoFullName),
			logging.Error("db_error", err))
		c.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to get onboarding"})
		return
	}

	c.JSON(http.StatusOK, reg)
}
