package api

import (
	"context"
	"fmt"

	argocdreg "github.com/madfam-org/enclii/apps/switchyard-api/internal/argocd"
)

type argoCDRegistrationRequest struct {
	ProjectName   string
	RepoFullName  string
	RepoURL       string
	Branch        string
	ManifestPath  string
	Namespace     string
	AppName       string
	ProjectConfig string
	CommitMessage string
	EnsureMode    bool
}

type argoCDRegistrationResult struct {
	Mode      string
	Action    string
	CommitSHA string
	AppName   string
}

func (h *Handler) registerArgoCDApplication(ctx context.Context, req argoCDRegistrationRequest) (argoCDRegistrationResult, error) {
	mode := argocdreg.NormalizeRegistrationMode("")
	if h != nil && h.config != nil {
		mode = argocdreg.NormalizeRegistrationMode(h.config.ArgocdRegistrationMode)
	}

	switch mode {
	case argocdreg.RegistrationModeGitOps:
		if h == nil || h.config == nil || !h.config.AllowLegacyGitOpsRegistration {
			return argoCDRegistrationResult{Mode: mode, AppName: req.AppName}, fmt.Errorf("legacy gitops argocd registration is disabled; set ENCLII_ALLOW_LEGACY_GITOPS_REGISTRATION=true only for documented break-glass migration work")
		}
		sha, err := h.commitLegacyArgoCDProjectConfig(ctx, req)
		action := "legacy_config_committed"
		if err != nil {
			action = "legacy_config_failed"
		}
		return argoCDRegistrationResult{
			Mode:      mode,
			Action:    action,
			CommitSHA: sha,
			AppName:   req.AppName,
		}, err
	case argocdreg.RegistrationModeRuntime:
		if h == nil || h.k8sClient == nil || h.k8sClient.DynamicClient == nil {
			return argoCDRegistrationResult{Mode: mode, AppName: req.AppName}, fmt.Errorf("argocd runtime reconciler not configured")
		}
		namespace := ""
		if h.config != nil {
			namespace = h.config.ArgocdNamespace
		}
		reconciler := argocdreg.NewApplicationReconciler(h.k8sClient.DynamicClient, namespace)
		result, err := reconciler.ReconcileApplication(ctx, argocdreg.DesiredApplication{
			AppName:              req.AppName,
			ProjectName:          req.ProjectName,
			RepoURL:              req.RepoURL,
			Branch:               req.Branch,
			ManifestPath:         req.ManifestPath,
			DestinationNamespace: req.Namespace,
		})
		if err != nil {
			return argoCDRegistrationResult{Mode: mode, AppName: req.AppName}, err
		}
		return argoCDRegistrationResult{
			Mode:    mode,
			Action:  result.Action,
			AppName: result.Name,
		}, nil
	default:
		return argoCDRegistrationResult{Mode: mode, AppName: req.AppName}, fmt.Errorf("unsupported argocd registration mode %q (expected %q or %q)", mode, argocdreg.RegistrationModeGitOps, argocdreg.RegistrationModeRuntime)
	}
}

func (h *Handler) commitLegacyArgoCDProjectConfig(ctx context.Context, req argoCDRegistrationRequest) (string, error) {
	if h == nil || h.config == nil || h.config.GitHubToken == "" || h.config.EncliiRepoOwner == "" || h.config.EncliiRepoName == "" {
		return "", fmt.Errorf("GitHub token or enclii repo not configured")
	}
	configFilePath := fmt.Sprintf("infra/argocd/projects/%s/config.json", req.ProjectName)
	commitMsg := req.CommitMessage
	if commitMsg == "" {
		if req.EnsureMode {
			commitMsg = fmt.Sprintf("chore(argocd): ensure %s onboarding config\n\nGenerated by POST /v1/admin/onboard/ensure for %s.", req.ProjectName, req.RepoFullName)
		} else {
			commitMsg = fmt.Sprintf("feat(argocd): auto-onboard %s\n\nGenerated by POST /v1/admin/onboard for %s\nApplicationSet auto-generates the ArgoCD Application from this config.", req.ProjectName, req.RepoFullName)
		}
	}

	return createOrUpdateGitHubFile(
		ctx, h.config.GitHubToken, h.config.EncliiRepoOwner, h.config.EncliiRepoName,
		configFilePath, []byte(req.ProjectConfig), commitMsg, "main",
	)
}
