package api

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"strings"
	"time"

	"github.com/gin-gonic/gin"
	"golang.org/x/text/cases"
	"golang.org/x/text/language"

	"github.com/madfam-org/enclii/apps/switchyard-api/internal/logging"
)

// statusServiceEntry represents a single service in the status page configmap.
type statusServiceEntry struct {
	Name        string `json:"name"`
	URL         string `json:"url"`
	Group       string `json:"group"`
	Description string `json:"description,omitempty"`
}

// coreEncliiServices returns the hardcoded status entries for enclii's own services.
// These are always included because they ARE enclii (not external projects).
func coreEncliiServices() []statusServiceEntry {
	return []statusServiceEntry{
		{Name: "api.enclii.dev", URL: "https://api.enclii.dev/health", Group: "Enclii", Description: "Switchyard API"},
		{Name: "app.enclii.dev", URL: "https://app.enclii.dev", Group: "Enclii", Description: "Web Dashboard"},
		{Name: "admin.enclii.dev", URL: "https://admin.enclii.dev", Group: "Enclii", Description: "Dispatch Admin"},
		{Name: "enclii.dev", URL: "https://enclii.dev", Group: "Enclii", Description: "Landing Page"},
		{Name: "auth.madfam.io", URL: "https://auth.madfam.io/health", Group: "Auth / Janua", Description: "SSO Identity Provider"},
	}
}

// ListStatusServices builds the complete service list from core enclii services
// plus all onboarded projects' status entries.
// GET /v1/admin/status/services
func (h *Handler) ListStatusServices(c *gin.Context) {
	ctx := c.Request.Context()

	services := coreEncliiServices()

	// Fetch onboarded projects and their status entries from DB
	regs, err := h.repos.Onboardings.List(ctx)
	if err != nil {
		h.logger.Warn(ctx, "Failed to list onboardings for status services",
			logging.Error("error", err))
	} else {
		for _, reg := range regs {
			if reg.ConfigSnapshot == nil {
				continue
			}
			if statusRaw, ok := reg.ConfigSnapshot["status_entries"]; ok {
				entriesJSON, _ := json.Marshal(statusRaw)
				var entries []statusServiceEntry
				if err := json.Unmarshal(entriesJSON, &entries); err == nil {
					services = append(services, entries...)
				}
			}
		}
	}

	c.JSON(http.StatusOK, gin.H{
		"count":    len(services),
		"services": services,
	})
}

// RegenerateStatusConfig rebuilds and commits the complete status configmap from scratch.
// POST /v1/admin/status/regenerate
func (h *Handler) RegenerateStatusConfig(c *gin.Context) {
	ctx := c.Request.Context()

	if h.config.GitHubToken == "" || h.config.EncliiRepoOwner == "" {
		c.JSON(http.StatusServiceUnavailable, gin.H{"error": "GitHub token or enclii repo not configured"})
		return
	}

	// Build complete service list
	allServices := coreEncliiServices()

	// Add entries from onboarded projects
	regs, err := h.repos.Onboardings.List(ctx)
	if err != nil {
		h.logger.Warn(ctx, "Failed to list onboardings for status regeneration",
			logging.Error("error", err))
	} else {
		for _, reg := range regs {
			entries := h.fetchStatusEntriesForProject(ctx, reg.RepoFullName)
			allServices = append(allServices, entries...)
		}
	}

	// Generate configmap YAML
	configmapYAML, err := generateStatusConfigmap(allServices)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": fmt.Sprintf("failed to generate configmap: %v", err)})
		return
	}

	// Commit to enclii repo
	configmapPath := "apps/status/k8s/madfam/configmap.yaml"
	commitMsg := fmt.Sprintf("feat(status): regenerate status configmap (%d services)\n\nRegenerated by POST /v1/admin/status/regenerate", len(allServices))

	commitSHA, commitErr := createOrUpdateGitHubFile(ctx, h.config.GitHubToken, h.config.EncliiRepoOwner, h.config.EncliiRepoName, configmapPath, configmapYAML, commitMsg, "main")
	if commitErr != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": fmt.Sprintf("failed to commit configmap: %v", commitErr)})
		return
	}

	h.logger.Info(ctx, "Regenerated status configmap",
		logging.Int("service_count", len(allServices)),
		logging.String("commit", commitSHA))

	c.JSON(http.StatusOK, gin.H{
		"status":        "regenerated",
		"service_count": len(allServices),
		"commit_sha":    commitSHA,
	})
}

// fetchStatusEntriesForProject reads a project's enclii.yaml and extracts status entries.
func (h *Handler) fetchStatusEntriesForProject(ctx context.Context, repoFullName string) []statusServiceEntry {
	config := h.fetchAndParseEncliiYAML(ctx, repoFullName, "HEAD")
	if config == nil || config.Spec.Status == nil {
		// Auto-derive from domains if no explicit status section
		if config != nil && len(config.Spec.Domains) > 0 {
			var entries []statusServiceEntry
			project := config.Metadata.Project
			if project == "" {
				parts := strings.SplitN(repoFullName, "/", 2)
				if len(parts) == 2 {
					project = parts[1]
				}
			}
			for _, d := range config.Spec.Domains {
				entries = append(entries, statusServiceEntry{
					Name:  d.Name,
					URL:   "https://" + d.Name,
					Group: cases.Title(language.English).String(project),
				})
			}
			return entries
		}
		return nil
	}

	var entries []statusServiceEntry
	for _, e := range config.Spec.Status.Entries {
		entries = append(entries, statusServiceEntry(e))
	}
	return entries
}

// generateStatusConfigmap produces the complete configmap YAML for the status page.
func generateStatusConfigmap(services []statusServiceEntry) ([]byte, error) {
	servicesJSON, err := json.MarshalIndent(services, "  ", "  ")
	if err != nil {
		return nil, fmt.Errorf("marshal services: %w", err)
	}

	yaml := fmt.Sprintf(`apiVersion: v1
kind: ConfigMap
metadata:
  name: status-config
  namespace: status
  labels:
    app: status-page
  annotations:
    configmap-version: "%s"
data:
  services-config: |
  %s
`, time.Now().UTC().Format("20060102T150405Z"), string(servicesJSON))

	return []byte(yaml), nil
}
