apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- rbac.yaml
- deployment.yaml
- service.yaml

images:
- digest: sha256:6acbb3fc5f45b54fc1cf2f4598d986749a2425ccde223d6ce06cc240867177f4
  name: ghcr.io/madfam-org/enclii/admin-console
  newName: ghcr.io/madfam-org/enclii/dispatch
