apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- rbac.yaml
- deployment.yaml
- service.yaml

images:
- digest: sha256:78d8f47c82dd2903143ff98d071742476fd13227829cb5a1fa0f35573dd88a53
  name: ghcr.io/madfam-org/enclii/admin-console
  newName: ghcr.io/madfam-org/enclii/dispatch
