apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- rbac.yaml
- deployment.yaml
- service.yaml

images:
- digest: sha256:b32efbef8369da7d7ae6575ca405bbabbfdd921dbdc1253d3941bdbe9111fee7
  name: ghcr.io/madfam-org/enclii/admin-console
  newName: ghcr.io/madfam-org/enclii/dispatch
